// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#ifndef _MUSIC_EVENTS_H
#define _MUSIC_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void music_loaded(lv_event_t * e);
void music_unloaded(lv_event_t * e);
void music_seek_released(lv_event_t * e);
void music_seek_pressed(lv_event_t * e);
void music_seek_value_changed(lv_event_t * e);
void music_action(lv_event_t * e);
void music_list_refresh(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
