// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#ifndef _UI_COMP_SIMPLEITEM_H
#define _UI_COMP_SIMPLEITEM_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT simpleitem
#define UI_COMP_SIMPLEITEM_SIMPLEITEM 0
#define UI_COMP_SIMPLEITEM_IMAGE14 1
#define UI_COMP_SIMPLEITEM_SIMPLE_ITEM_TEXT 2
#define _UI_COMP_SIMPLEITEM_NUM 3
lv_obj_t * ui_simpleitem_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
