// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#include "../ui.h"

// COMPONENT toast

lv_obj_t * ui_toast_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_toast;
    cui_toast = lv_label_create(comp_parent);
    lv_obj_set_width(cui_toast, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_toast, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_toast, 0);
    lv_obj_set_y(cui_toast, lv_pct(30));
    lv_obj_set_align(cui_toast, LV_ALIGN_CENTER);
    lv_label_set_text(cui_toast, "Toast");
    lv_obj_add_flag(cui_toast, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(cui_toast, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(cui_toast, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_toast, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_toast, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_toast, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_toast, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_toast, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_toast, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_TOAST_NUM);
    children[UI_COMP_TOAST_TOAST] = cui_toast;
    lv_obj_add_event_cb(cui_toast, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_toast, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_toast_create_hook(cui_toast);
    return cui_toast;
}

