// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#ifndef _UI_COMP_TOAST_H
#define _UI_COMP_TOAST_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT toast
#define UI_COMP_TOAST_TOAST 0
#define _UI_COMP_TOAST_NUM 1
lv_obj_t * ui_toast_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
