// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#ifndef _UI_COMP_VOLUMESLIDER_H
#define _UI_COMP_VOLUMESLIDER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT volumeslider
#define UI_COMP_VOLUMESLIDER_VOLUMESLIDER 0
#define UI_COMP_VOLUMESLIDER_IMAGE17 1
#define _UI_COMP_VOLUMESLIDER_NUM 2
lv_obj_t * ui_volumeslider_create(lv_obj_t * comp_parent);
void ui_event_comp_volumeslider_volumeslider(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
