// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#include "../ui.h"

// COMPONENT simpleitem

lv_obj_t * ui_simpleitem_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_simpleitem;
    cui_simpleitem = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_simpleitem);
    lv_obj_set_height(cui_simpleitem, 50);
    lv_obj_set_width(cui_simpleitem, lv_pct(95));
    lv_obj_set_align(cui_simpleitem, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(cui_simpleitem, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_simpleitem, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(cui_simpleitem, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(cui_simpleitem, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_simpleitem, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_simpleitem, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_simpleitem, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_simpleitem, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(cui_simpleitem, 20, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_t * cui_Image14;
    cui_Image14 = lv_image_create(cui_simpleitem);
    lv_image_set_src(cui_Image14, &ui_img_item_music_png);
    lv_obj_set_width(cui_Image14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Image14, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(cui_Image14, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_simple_item_text;
    cui_simple_item_text = lv_label_create(cui_simpleitem);
    lv_obj_set_height(cui_simple_item_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(cui_simple_item_text, 1);
    lv_obj_set_x(cui_simple_item_text, 32);
    lv_obj_set_y(cui_simple_item_text, 0);
    lv_obj_set_align(cui_simple_item_text, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(cui_simple_item_text, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(cui_simple_item_text, "文本");
    lv_obj_set_style_text_color(cui_simple_item_text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_simple_item_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_simple_item_text, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_simple_item_text, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_simple_item_text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_simple_item_text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_simple_item_text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_SIMPLEITEM_NUM);
    children[UI_COMP_SIMPLEITEM_SIMPLEITEM] = cui_simpleitem;
    children[UI_COMP_SIMPLEITEM_IMAGE14] = cui_Image14;
    children[UI_COMP_SIMPLEITEM_SIMPLE_ITEM_TEXT] = cui_simple_item_text;
    lv_obj_add_event_cb(cui_simpleitem, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_simpleitem, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_simpleitem_create_hook(cui_simpleitem);
    return cui_simpleitem;
}

