// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#include "../ui.h"

void ui_event_comp_volumeslider_volumeslider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_volumeslider = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        volume_change(e);
    }
}

// COMPONENT volumeslider

lv_obj_t * ui_volumeslider_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_volumeslider;
    cui_volumeslider = lv_slider_create(comp_parent);
    lv_slider_set_value(cui_volumeslider, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(cui_volumeslider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(cui_volumeslider, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_height(cui_volumeslider, 40);
    lv_obj_set_width(cui_volumeslider, lv_pct(50));
    lv_obj_set_x(cui_volumeslider, lv_pct(0));
    lv_obj_set_y(cui_volumeslider, lv_pct(10));
    lv_obj_set_align(cui_volumeslider, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(cui_volumeslider, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(cui_volumeslider, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_volumeslider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_volumeslider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(cui_volumeslider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_volumeslider, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_volumeslider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(cui_volumeslider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_volumeslider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(cui_volumeslider, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(cui_volumeslider,
                                                                                                    lv_obj_get_style_pad_right(cui_volumeslider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_t * cui_Image17;
    cui_Image17 = lv_image_create(cui_volumeslider);
    lv_image_set_src(cui_Image17, &ui_img_icon_volume_png);
    lv_obj_set_width(cui_Image17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image17, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_VOLUMESLIDER_NUM);
    children[UI_COMP_VOLUMESLIDER_VOLUMESLIDER] = cui_volumeslider;
    children[UI_COMP_VOLUMESLIDER_IMAGE17] = cui_Image17;
    lv_obj_add_event_cb(cui_volumeslider, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_volumeslider, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_volumeslider, ui_event_comp_volumeslider_volumeslider, LV_EVENT_ALL, children);
    ui_comp_volumeslider_create_hook(cui_volumeslider);
    return cui_volumeslider;
}

