// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#include "../ui.h"

void ui_comp_simpleitem_create_hook(lv_obj_t * comp)
{
}

void ui_comp_toast_create_hook(lv_obj_t * comp)
{
}

void ui_comp_volumeslider_create_hook(lv_obj_t * comp)
{
}
