// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#ifndef UI_BOOT_H
#define UI_BOOT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_boot
extern void ui_boot_screen_init(void);
extern void ui_boot_screen_destroy(void);
extern void ui_event_boot(lv_event_t * e);
extern lv_obj_t * ui_boot;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_bootbar;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

