// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#include "../ui.h"

lv_obj_t * ui_boot = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_bootbar = NULL;
// event funtions
void ui_event_boot(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        bootinit(e);
    }
}

// build funtions

void ui_boot_screen_init(void)
{
    ui_boot = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_boot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_boot, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_boot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_image_create(ui_boot);
    lv_image_set_src(ui_Image7, &ui_img_apple_logo_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bootbar = lv_bar_create(ui_boot);
    lv_obj_set_width(ui_bootbar, 150);
    lv_obj_set_height(ui_bootbar, 10);
    lv_obj_set_x(ui_bootbar, 0);
    lv_obj_set_y(ui_bootbar, 85);
    lv_obj_set_align(ui_bootbar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_bootbar, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bootbar, lv_color_hex(0x7E7E7E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bootbar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_anim_duration(ui_bootbar, 2000, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_bootbar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bootbar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_bootbar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_bootbar,
                                                                                              lv_obj_get_style_pad_right(ui_bootbar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_add_event_cb(ui_boot, ui_event_boot, LV_EVENT_ALL, NULL);

}

void ui_boot_screen_destroy(void)
{
    if(ui_boot) lv_obj_del(ui_boot);

    // NULL screen variables
    ui_boot = NULL;
    ui_Image7 = NULL;
    ui_bootbar = NULL;

}
