// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#ifndef UI_CALENDAR_H
#define UI_CALENDAR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_calendar
extern void ui_calendar_screen_init(void);
extern void ui_calendar_screen_destroy(void);
extern void ui_event_calendar(lv_event_t * e);
extern lv_obj_t * ui_calendar;
extern lv_obj_t * ui_Container75;
extern lv_obj_t * ui_Calendar_widget;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

