// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#ifndef UI_CALCULATOR_H
#define UI_CALCULATOR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_calculator
extern void ui_calculator_screen_init(void);
extern void ui_calculator_screen_destroy(void);
extern void ui_event_calculator(lv_event_t * e);
extern lv_obj_t * ui_calculator;
extern void ui_event_Container1(lv_event_t * e);
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label2;
extern void ui_event_Container7(lv_event_t * e);
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Label7;
extern void ui_event_Container8(lv_event_t * e);
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Label8;
extern void ui_event_Container9(lv_event_t * e);
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Label9;
extern void ui_event_Container10(lv_event_t * e);
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Label10;
extern void ui_event_Container11(lv_event_t * e);
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Label11;
extern void ui_event_Container12(lv_event_t * e);
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_Label12;
extern void ui_event_Container13(lv_event_t * e);
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_Label13;
extern void ui_event_Container14(lv_event_t * e);
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_Label14;
extern void ui_event_Container15(lv_event_t * e);
extern lv_obj_t * ui_Container15;
extern lv_obj_t * ui_Label15;
extern void ui_event_Container16(lv_event_t * e);
extern lv_obj_t * ui_Container16;
extern lv_obj_t * ui_Label16;
extern void ui_event_Container17(lv_event_t * e);
extern lv_obj_t * ui_Container17;
extern lv_obj_t * ui_Label17;
extern void ui_event_Container18(lv_event_t * e);
extern lv_obj_t * ui_Container18;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Container19;
extern lv_obj_t * ui_Label19;
extern void ui_event_Container20(lv_event_t * e);
extern lv_obj_t * ui_Container20;
extern lv_obj_t * ui_Label20;
extern void ui_event_Container21(lv_event_t * e);
extern lv_obj_t * ui_Container21;
extern lv_obj_t * ui_Label21;
extern void ui_event_Container22(lv_event_t * e);
extern lv_obj_t * ui_Container22;
extern lv_obj_t * ui_Label22;
extern void ui_event_Container23(lv_event_t * e);
extern lv_obj_t * ui_Container23;
extern lv_obj_t * ui_Label23;
extern void ui_event_Container24(lv_event_t * e);
extern lv_obj_t * ui_Container24;
extern lv_obj_t * ui_Label24;
extern void ui_event_Container25(lv_event_t * e);
extern lv_obj_t * ui_Container25;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

