// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#include "../ui.h"

lv_obj_t * ui_calculator = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Container8 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Container9 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Container10 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Container11 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Container12 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Container13 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Container14 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Container15 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Container16 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Container17 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Container18 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Container19 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_Container20 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_Container21 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_Container22 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_Container23 = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_Container24 = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_Container25 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_Label6 = NULL;
// event funtions
void ui_event_calculator(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_label_set_property(ui_Label6, _UI_LABEL_PROPERTY_TEXT, "0");
    }
}

void ui_event_Container1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_Label6, _UI_LABEL_PROPERTY_TEXT, "7");
    }
}

void ui_event_Container7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_Label6, _UI_LABEL_PROPERTY_TEXT, "8");
    }
}

void ui_event_Container8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_Label6, _UI_LABEL_PROPERTY_TEXT, "9");
    }
}

void ui_event_Container9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_Label6, _UI_LABEL_PROPERTY_TEXT, "x");
    }
}

void ui_event_Container10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_Label6, _UI_LABEL_PROPERTY_TEXT, "4");
    }
}

void ui_event_Container11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_Label6, _UI_LABEL_PROPERTY_TEXT, "5");
    }
}

void ui_event_Container12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_Label6, _UI_LABEL_PROPERTY_TEXT, "6");
    }
}

void ui_event_Container13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_Label6, _UI_LABEL_PROPERTY_TEXT, "-");
    }
}

void ui_event_Container14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_Label6, _UI_LABEL_PROPERTY_TEXT, "1");
    }
}

void ui_event_Container15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_Label6, _UI_LABEL_PROPERTY_TEXT, "2");
    }
}

void ui_event_Container16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_Label6, _UI_LABEL_PROPERTY_TEXT, "3");
    }
}

void ui_event_Container17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_Label6, _UI_LABEL_PROPERTY_TEXT, "+");
    }
}

void ui_event_Container18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_Label6, _UI_LABEL_PROPERTY_TEXT, "00");
    }
}

void ui_event_Container20(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_Label6, _UI_LABEL_PROPERTY_TEXT, ".");
    }
}

void ui_event_Container21(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_Label6, _UI_LABEL_PROPERTY_TEXT, "0");
    }
}

void ui_event_Container22(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_Label6, _UI_LABEL_PROPERTY_TEXT, "0");
    }
}

void ui_event_Container23(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_Label6, _UI_LABEL_PROPERTY_TEXT, "(");
    }
}

void ui_event_Container24(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_Label6, _UI_LABEL_PROPERTY_TEXT, ")");
    }
}

void ui_event_Container25(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_Label6, _UI_LABEL_PROPERTY_TEXT, "/");
    }
}

// build funtions

void ui_calculator_screen_init(void)
{
    ui_calculator = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_calculator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_calculator);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 50);
    lv_obj_set_height(ui_Container1, 40);
    lv_obj_set_x(ui_Container1, 8);
    lv_obj_set_y(ui_Container1, 128);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Container1, 8, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0xBBBBBB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label2 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "7");

    ui_Container7 = lv_obj_create(ui_calculator);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 50);
    lv_obj_set_height(ui_Container7, 40);
    lv_obj_set_x(ui_Container7, 66);
    lv_obj_set_y(ui_Container7, 128);
    lv_obj_remove_flag(ui_Container7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container7, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container7, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Container7, 8, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Container7, lv_color_hex(0xBBBBBB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Container7, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label7 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "8");

    ui_Container8 = lv_obj_create(ui_calculator);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 50);
    lv_obj_set_height(ui_Container8, 40);
    lv_obj_set_x(ui_Container8, 124);
    lv_obj_set_y(ui_Container8, 128);
    lv_obj_remove_flag(ui_Container8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container8, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container8, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Container8, 8, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Container8, lv_color_hex(0xBBBBBB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Container8, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label8 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "9");

    ui_Container9 = lv_obj_create(ui_calculator);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 50);
    lv_obj_set_height(ui_Container9, 40);
    lv_obj_set_x(ui_Container9, 182);
    lv_obj_set_y(ui_Container9, 128);
    lv_obj_remove_flag(ui_Container9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container9, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container9, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Container9, 8, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Container9, lv_color_hex(0xBBBBBB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Container9, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label9 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "x");

    ui_Container10 = lv_obj_create(ui_calculator);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, 50);
    lv_obj_set_height(ui_Container10, 40);
    lv_obj_set_x(ui_Container10, 8);
    lv_obj_set_y(ui_Container10, 176);
    lv_obj_remove_flag(ui_Container10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container10, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container10, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Container10, 8, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Container10, lv_color_hex(0xBBBBBB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Container10, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label10 = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "4");

    ui_Container11 = lv_obj_create(ui_calculator);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_width(ui_Container11, 50);
    lv_obj_set_height(ui_Container11, 40);
    lv_obj_set_x(ui_Container11, 66);
    lv_obj_set_y(ui_Container11, 176);
    lv_obj_remove_flag(ui_Container11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container11, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container11, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Container11, 8, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Container11, lv_color_hex(0xBBBBBB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Container11, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label11 = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "5");

    ui_Container12 = lv_obj_create(ui_calculator);
    lv_obj_remove_style_all(ui_Container12);
    lv_obj_set_width(ui_Container12, 50);
    lv_obj_set_height(ui_Container12, 40);
    lv_obj_set_x(ui_Container12, 124);
    lv_obj_set_y(ui_Container12, 176);
    lv_obj_remove_flag(ui_Container12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container12, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container12, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Container12, 8, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Container12, lv_color_hex(0xBBBBBB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Container12, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label12 = lv_label_create(ui_Container12);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "6");

    ui_Container13 = lv_obj_create(ui_calculator);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_width(ui_Container13, 50);
    lv_obj_set_height(ui_Container13, 40);
    lv_obj_set_x(ui_Container13, 182);
    lv_obj_set_y(ui_Container13, 176);
    lv_obj_remove_flag(ui_Container13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container13, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container13, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Container13, 8, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Container13, lv_color_hex(0xBBBBBB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Container13, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label13 = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "-");

    ui_Container14 = lv_obj_create(ui_calculator);
    lv_obj_remove_style_all(ui_Container14);
    lv_obj_set_width(ui_Container14, 50);
    lv_obj_set_height(ui_Container14, 40);
    lv_obj_set_x(ui_Container14, 8);
    lv_obj_set_y(ui_Container14, 224);
    lv_obj_remove_flag(ui_Container14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container14, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container14, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Container14, 8, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Container14, lv_color_hex(0xBBBBBB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Container14, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label14 = lv_label_create(ui_Container14);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "1");

    ui_Container15 = lv_obj_create(ui_calculator);
    lv_obj_remove_style_all(ui_Container15);
    lv_obj_set_width(ui_Container15, 50);
    lv_obj_set_height(ui_Container15, 40);
    lv_obj_set_x(ui_Container15, 66);
    lv_obj_set_y(ui_Container15, 224);
    lv_obj_remove_flag(ui_Container15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container15, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container15, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Container15, 8, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Container15, lv_color_hex(0xBBBBBB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Container15, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label15 = lv_label_create(ui_Container15);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "2");

    ui_Container16 = lv_obj_create(ui_calculator);
    lv_obj_remove_style_all(ui_Container16);
    lv_obj_set_width(ui_Container16, 50);
    lv_obj_set_height(ui_Container16, 40);
    lv_obj_set_x(ui_Container16, 124);
    lv_obj_set_y(ui_Container16, 224);
    lv_obj_remove_flag(ui_Container16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container16, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container16, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Container16, 8, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Container16, lv_color_hex(0xBBBBBB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Container16, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label16 = lv_label_create(ui_Container16);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "3");

    ui_Container17 = lv_obj_create(ui_calculator);
    lv_obj_remove_style_all(ui_Container17);
    lv_obj_set_width(ui_Container17, 50);
    lv_obj_set_height(ui_Container17, 40);
    lv_obj_set_x(ui_Container17, 182);
    lv_obj_set_y(ui_Container17, 224);
    lv_obj_remove_flag(ui_Container17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container17, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container17, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Container17, 8, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Container17, lv_color_hex(0xBBBBBB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Container17, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label17 = lv_label_create(ui_Container17);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "+");

    ui_Container18 = lv_obj_create(ui_calculator);
    lv_obj_remove_style_all(ui_Container18);
    lv_obj_set_width(ui_Container18, 50);
    lv_obj_set_height(ui_Container18, 40);
    lv_obj_set_x(ui_Container18, 8);
    lv_obj_set_y(ui_Container18, 272);
    lv_obj_remove_flag(ui_Container18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container18, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container18, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Container18, 8, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Container18, lv_color_hex(0xBBBBBB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Container18, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label18 = lv_label_create(ui_Container18);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "00");

    ui_Container19 = lv_obj_create(ui_calculator);
    lv_obj_remove_style_all(ui_Container19);
    lv_obj_set_width(ui_Container19, 50);
    lv_obj_set_height(ui_Container19, 40);
    lv_obj_set_x(ui_Container19, 66);
    lv_obj_set_y(ui_Container19, 272);
    lv_obj_remove_flag(ui_Container19, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container19, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container19, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Container19, 8, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Container19, lv_color_hex(0xBBBBBB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Container19, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label19 = lv_label_create(ui_Container19);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "0");

    ui_Container20 = lv_obj_create(ui_calculator);
    lv_obj_remove_style_all(ui_Container20);
    lv_obj_set_width(ui_Container20, 50);
    lv_obj_set_height(ui_Container20, 40);
    lv_obj_set_x(ui_Container20, 124);
    lv_obj_set_y(ui_Container20, 272);
    lv_obj_remove_flag(ui_Container20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container20, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container20, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Container20, 8, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Container20, lv_color_hex(0xBBBBBB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Container20, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label20 = lv_label_create(ui_Container20);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, ".");

    ui_Container21 = lv_obj_create(ui_calculator);
    lv_obj_remove_style_all(ui_Container21);
    lv_obj_set_width(ui_Container21, 50);
    lv_obj_set_height(ui_Container21, 40);
    lv_obj_set_x(ui_Container21, 182);
    lv_obj_set_y(ui_Container21, 272);
    lv_obj_remove_flag(ui_Container21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container21, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container21, lv_color_hex(0xFFAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Container21, 8, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Container21, lv_color_hex(0xFFBBBB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Container21, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label21 = lv_label_create(ui_Container21);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "=");

    ui_Container22 = lv_obj_create(ui_calculator);
    lv_obj_remove_style_all(ui_Container22);
    lv_obj_set_width(ui_Container22, 50);
    lv_obj_set_height(ui_Container22, 40);
    lv_obj_set_x(ui_Container22, 8);
    lv_obj_set_y(ui_Container22, 80);
    lv_obj_add_flag(ui_Container22, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_Container22, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container22, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container22, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Container22, 8, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Container22, lv_color_hex(0xBBBBBB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Container22, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label22 = lv_label_create(ui_Container22);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "AC");

    ui_Container23 = lv_obj_create(ui_calculator);
    lv_obj_remove_style_all(ui_Container23);
    lv_obj_set_width(ui_Container23, 50);
    lv_obj_set_height(ui_Container23, 40);
    lv_obj_set_x(ui_Container23, 66);
    lv_obj_set_y(ui_Container23, 80);
    lv_obj_remove_flag(ui_Container23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container23, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container23, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Container23, 8, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Container23, lv_color_hex(0xBBBBBB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Container23, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label23 = lv_label_create(ui_Container23);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "(");

    ui_Container24 = lv_obj_create(ui_calculator);
    lv_obj_remove_style_all(ui_Container24);
    lv_obj_set_width(ui_Container24, 50);
    lv_obj_set_height(ui_Container24, 40);
    lv_obj_set_x(ui_Container24, 124);
    lv_obj_set_y(ui_Container24, 80);
    lv_obj_remove_flag(ui_Container24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container24, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container24, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Container24, 8, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Container24, lv_color_hex(0xBBBBBB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Container24, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label24 = lv_label_create(ui_Container24);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, ")");

    ui_Container25 = lv_obj_create(ui_calculator);
    lv_obj_remove_style_all(ui_Container25);
    lv_obj_set_width(ui_Container25, 50);
    lv_obj_set_height(ui_Container25, 40);
    lv_obj_set_x(ui_Container25, 182);
    lv_obj_set_y(ui_Container25, 80);
    lv_obj_remove_flag(ui_Container25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container25, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container25, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Container25, 8, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Container25, lv_color_hex(0xBBBBBB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Container25, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label25 = lv_label_create(ui_Container25);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "/");

    ui_Container6 = lv_obj_create(ui_calculator);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 224);
    lv_obj_set_height(ui_Container6, 70);
    lv_obj_set_x(ui_Container6, 0);
    lv_obj_set_y(ui_Container6, 1);
    lv_obj_set_align(ui_Container6, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label6, lv_pct(100));
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label6, "");
    lv_obj_remove_flag(ui_Label6, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Label6, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_align(ui_Label6, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Container1, ui_event_Container1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container7, ui_event_Container7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container8, ui_event_Container8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container9, ui_event_Container9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container10, ui_event_Container10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container11, ui_event_Container11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container12, ui_event_Container12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container13, ui_event_Container13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container14, ui_event_Container14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container15, ui_event_Container15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container16, ui_event_Container16, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container17, ui_event_Container17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container18, ui_event_Container18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container20, ui_event_Container20, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container21, ui_event_Container21, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container22, ui_event_Container22, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container23, ui_event_Container23, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container24, ui_event_Container24, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container25, ui_event_Container25, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_calculator, ui_event_calculator, LV_EVENT_ALL, NULL);

}

void ui_calculator_screen_destroy(void)
{
    if(ui_calculator) lv_obj_del(ui_calculator);

    // NULL screen variables
    ui_calculator = NULL;
    ui_Container1 = NULL;
    ui_Label2 = NULL;
    ui_Container7 = NULL;
    ui_Label7 = NULL;
    ui_Container8 = NULL;
    ui_Label8 = NULL;
    ui_Container9 = NULL;
    ui_Label9 = NULL;
    ui_Container10 = NULL;
    ui_Label10 = NULL;
    ui_Container11 = NULL;
    ui_Label11 = NULL;
    ui_Container12 = NULL;
    ui_Label12 = NULL;
    ui_Container13 = NULL;
    ui_Label13 = NULL;
    ui_Container14 = NULL;
    ui_Label14 = NULL;
    ui_Container15 = NULL;
    ui_Label15 = NULL;
    ui_Container16 = NULL;
    ui_Label16 = NULL;
    ui_Container17 = NULL;
    ui_Label17 = NULL;
    ui_Container18 = NULL;
    ui_Label18 = NULL;
    ui_Container19 = NULL;
    ui_Label19 = NULL;
    ui_Container20 = NULL;
    ui_Label20 = NULL;
    ui_Container21 = NULL;
    ui_Label21 = NULL;
    ui_Container22 = NULL;
    ui_Label22 = NULL;
    ui_Container23 = NULL;
    ui_Label23 = NULL;
    ui_Container24 = NULL;
    ui_Label24 = NULL;
    ui_Container25 = NULL;
    ui_Label25 = NULL;
    ui_Container6 = NULL;
    ui_Label6 = NULL;

}
