// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#ifndef UI_FILE_MANAGER_H
#define UI_FILE_MANAGER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_file_manager
extern void ui_file_manager_screen_init(void);
extern void ui_file_manager_screen_destroy(void);
extern lv_obj_t * ui_file_manager;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

