// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#ifndef UI_FILE_MANAGER_H
#define UI_FILE_MANAGER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_file_manager
extern void ui_file_manager_screen_init(void);
extern void ui_file_manager_screen_destroy(void);
extern void ui_event_file_manager(lv_event_t * e);
extern lv_obj_t * ui_file_manager;
extern lv_obj_t * ui_Container54;
extern lv_obj_t * ui_file_name;
extern void ui_event_Label40(lv_event_t * e);
extern lv_obj_t * ui_Label40;
extern void ui_event_Label42(lv_event_t * e);
extern lv_obj_t * ui_Label42;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

