// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#include "../ui.h"

lv_obj_t * ui_file_manager = NULL;
lv_obj_t * ui_Container54 = NULL;
lv_obj_t * ui_file_name = NULL;
lv_obj_t * ui_Label40 = NULL;
lv_obj_t * ui_Label42 = NULL;
// event funtions
void ui_event_file_manager(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        file_manager_loaded(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        file_manager_unloaded(e);
    }
}

void ui_event_Label40(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        file_del(e);
    }
}

void ui_event_Label42(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        file_act_close(e);
    }
}

// build funtions

void ui_file_manager_screen_init(void)
{
    ui_file_manager = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_file_manager, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container54 = lv_obj_create(ui_file_manager);
    lv_obj_remove_style_all(ui_Container54);
    lv_obj_set_width(ui_Container54, lv_pct(60));
    lv_obj_set_height(ui_Container54, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Container54, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container54, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container54, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Container54, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Container54, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Container54, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container54, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container54, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Container54, lv_color_hex(0x777777), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Container54, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Container54, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Container54, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Container54, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Container54, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_file_name = lv_label_create(ui_Container54);
    lv_obj_set_width(ui_file_name, lv_pct(100));
    lv_obj_set_height(ui_file_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_file_name, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_file_name, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_file_name, "");
    lv_obj_set_style_text_align(ui_file_name, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_file_name, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_file_name, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_file_name, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_file_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label40 = lv_label_create(ui_Container54);
    lv_obj_set_width(ui_Label40, lv_pct(100));
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "删除");
    lv_obj_add_flag(ui_Label40, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Label40, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Label40, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label40, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label40, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label40, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label40, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label40, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label40, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label42 = lv_label_create(ui_Container54);
    lv_obj_set_width(ui_Label42, lv_pct(100));
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "关闭");
    lv_obj_add_flag(ui_Label42, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Label42, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Label42, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label42, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label42, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label42, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label42, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label42, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label42, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label42, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Label40, ui_event_Label40, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label42, ui_event_Label42, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_file_manager, ui_event_file_manager, LV_EVENT_ALL, NULL);

}

void ui_file_manager_screen_destroy(void)
{
    if(ui_file_manager) lv_obj_del(ui_file_manager);

    // NULL screen variables
    ui_file_manager = NULL;
    ui_Container54 = NULL;
    ui_file_name = NULL;
    ui_Label40 = NULL;
    ui_Label42 = NULL;

}
