// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#include "../ui.h"

lv_obj_t * ui_gaming = NULL;
lv_obj_t * ui_game_video = NULL;
lv_obj_t * ui_Container50 = NULL;
lv_obj_t * ui_Label36 = NULL;
lv_obj_t * ui_game_sound_label = NULL;
lv_obj_t * ui_Label38 = NULL;
// event funtions
void ui_event_gaming(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        gaming_paused(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        gaming_loaded(e);
    }
}

void ui_event_Label36(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        gaming_resume(e);
    }
}

void ui_event_game_sound_label(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        change_game_sound(e);
    }
}

void ui_event_Label38(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        gaming_exit(e);
    }
}

// build funtions

void ui_gaming_screen_init(void)
{
    ui_gaming = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_gaming, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_gaming, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gaming, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_game_video = lv_image_create(ui_gaming);
    lv_obj_set_width(ui_game_video, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_game_video, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_game_video, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_game_video, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_game_video, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container50 = lv_obj_create(ui_gaming);
    lv_obj_remove_style_all(ui_Container50);
    lv_obj_set_width(ui_Container50, lv_pct(60));
    lv_obj_set_height(ui_Container50, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Container50, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container50, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container50, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Container50, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Container50, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Container50, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container50, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container50, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Container50, lv_color_hex(0x777777), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Container50, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Container50, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Container50, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Container50, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Container50, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label36 = lv_label_create(ui_Container50);
    lv_obj_set_width(ui_Label36, lv_pct(100));
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "继续游戏");
    lv_obj_add_flag(ui_Label36, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Label36, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Label36, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label36, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label36, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label36, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label36, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label36, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label36, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_game_sound_label = lv_label_create(ui_Container50);
    lv_obj_set_width(ui_game_sound_label, lv_pct(100));
    lv_obj_set_height(ui_game_sound_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_game_sound_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_game_sound_label, "关闭声音");
    lv_obj_add_flag(ui_game_sound_label, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_game_sound_label,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);    /// Flags
    lv_obj_set_style_text_color(ui_game_sound_label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_game_sound_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_game_sound_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_game_sound_label, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_game_sound_label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_game_sound_label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_game_sound_label, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_game_sound_label, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label38 = lv_label_create(ui_Container50);
    lv_obj_set_width(ui_Label38, lv_pct(100));
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "退出");
    lv_obj_add_flag(ui_Label38, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Label38, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Label38, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label38, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label38, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label38, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label38, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label38, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label38, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Label36, ui_event_Label36, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_game_sound_label, ui_event_game_sound_label, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label38, ui_event_Label38, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_gaming, ui_event_gaming, LV_EVENT_ALL, NULL);

}

void ui_gaming_screen_destroy(void)
{
    if(ui_gaming) lv_obj_del(ui_gaming);

    // NULL screen variables
    ui_gaming = NULL;
    ui_game_video = NULL;
    ui_Container50 = NULL;
    ui_Label36 = NULL;
    ui_game_sound_label = NULL;
    ui_Label38 = NULL;

}
