// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#ifndef UI_GAMING_H
#define UI_GAMING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_gaming
extern void ui_gaming_screen_init(void);
extern void ui_gaming_screen_destroy(void);
extern void ui_event_gaming(lv_event_t * e);
extern lv_obj_t * ui_gaming;
extern lv_obj_t * ui_game_video;
extern lv_obj_t * ui_Container50;
extern void ui_event_Label36(lv_event_t * e);
extern lv_obj_t * ui_Label36;
extern void ui_event_game_sound_label(lv_event_t * e);
extern lv_obj_t * ui_game_sound_label;
extern void ui_event_Label38(lv_event_t * e);
extern lv_obj_t * ui_Label38;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

