// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#ifndef UI_HEALTH_H
#define UI_HEALTH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_health
extern void ui_health_screen_init(void);
extern void ui_health_screen_destroy(void);
extern lv_obj_t * ui_health;
extern lv_obj_t * ui_Container72;
extern lv_obj_t * ui_Container71;
extern lv_obj_t * ui_Container69;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label54;
extern lv_obj_t * ui_Label55;
extern lv_obj_t * ui_Container70;
extern lv_obj_t * ui_Image24;
extern lv_obj_t * ui_Label56;
extern lv_obj_t * ui_Container31;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Container36;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Label29;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

