// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#include "../ui.h"

lv_obj_t * ui_health = NULL;
lv_obj_t * ui_Container31 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label28 = NULL;
lv_obj_t * ui_Label30 = NULL;
lv_obj_t * ui_Container36 = NULL;
lv_obj_t * ui_Image11 = NULL;
lv_obj_t * ui_Label29 = NULL;
lv_obj_t * ui_Container32 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label31 = NULL;
lv_obj_t * ui_Label33 = NULL;
lv_obj_t * ui_Container34 = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_Label34 = NULL;
// event funtions
void ui_event_health(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_launcher, LV_SCR_LOAD_ANIM_OUT_RIGHT, 300, 0, &ui_launcher_screen_init);
    }
}

// build funtions

void ui_health_screen_init(void)
{
    ui_health = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_health, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_health, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_health, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_health, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_health, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_health, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container31 = lv_obj_create(ui_health);
    lv_obj_remove_style_all(ui_Container31);
    lv_obj_set_height(ui_Container31, 80);
    lv_obj_set_width(ui_Container31, lv_pct(100));
    lv_obj_set_align(ui_Container31, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Container31, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container31, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container31, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_button_create(ui_Container31);
    lv_obj_set_width(ui_Button1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Button1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Button1, -10);
    lv_obj_set_y(ui_Button1, -10);
    lv_obj_set_align(ui_Button1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "测量");
    lv_obj_set_style_text_font(ui_Label28, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label28, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label28, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label28, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label28, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_Container31);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, lv_pct(10));
    lv_obj_set_y(ui_Label30, lv_pct(55));
    lv_label_set_text(ui_Label30, "心率是心脏跳动的频率");
    lv_obj_set_style_text_font(ui_Label30, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container36 = lv_obj_create(ui_Container31);
    lv_obj_remove_style_all(ui_Container36);
    lv_obj_set_width(ui_Container36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Container36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Container36, lv_pct(10));
    lv_obj_set_y(ui_Container36, lv_pct(20));
    lv_obj_set_flex_flow(ui_Container36, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container36, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container36, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image11 = lv_image_create(ui_Container36);
    lv_image_set_src(ui_Image11, &ui_img_icon_heart_rate_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image11, lv_pct(10));
    lv_obj_set_y(ui_Image11, lv_pct(20));
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label29 = lv_label_create(ui_Container36);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, lv_pct(25));
    lv_obj_set_y(ui_Label29, lv_pct(20));
    lv_label_set_text(ui_Label29, "心率");
    lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label29, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label29, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container32 = lv_obj_create(ui_health);
    lv_obj_remove_style_all(ui_Container32);
    lv_obj_set_height(ui_Container32, 80);
    lv_obj_set_width(ui_Container32, lv_pct(100));
    lv_obj_set_x(ui_Container32, 0);
    lv_obj_set_y(ui_Container32, 85);
    lv_obj_set_align(ui_Container32, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Container32, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container32, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container32, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_button_create(ui_Container32);
    lv_obj_set_width(ui_Button2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Button2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Button2, -10);
    lv_obj_set_y(ui_Button2, -10);
    lv_obj_set_align(ui_Button2, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "测量");
    lv_obj_set_style_text_font(ui_Label31, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label31, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label31, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label31, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label31, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_Container32);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, lv_pct(10));
    lv_obj_set_y(ui_Label33, lv_pct(55));
    lv_label_set_text(ui_Label33, "血液中氧气的浓度");
    lv_obj_set_style_text_font(ui_Label33, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container34 = lv_obj_create(ui_Container32);
    lv_obj_remove_style_all(ui_Container34);
    lv_obj_set_width(ui_Container34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Container34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Container34, lv_pct(10));
    lv_obj_set_y(ui_Container34, lv_pct(20));
    lv_obj_set_flex_flow(ui_Container34, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container34, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container34, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image13 = lv_image_create(ui_Container34);
    lv_image_set_src(ui_Image13, &ui_img_icon_spo2_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image13, lv_pct(10));
    lv_obj_set_y(ui_Image13, lv_pct(20));
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label34 = lv_label_create(ui_Container34);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, lv_pct(25));
    lv_obj_set_y(ui_Label34, lv_pct(20));
    lv_label_set_text(ui_Label34, "血氧");
    lv_obj_set_style_text_color(ui_Label34, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label34, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label34, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label34, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label34, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label34, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_health, ui_event_health, LV_EVENT_ALL, NULL);

}

void ui_health_screen_destroy(void)
{
    if(ui_health) lv_obj_del(ui_health);

    // NULL screen variables
    ui_health = NULL;
    ui_Container31 = NULL;
    ui_Button1 = NULL;
    ui_Label28 = NULL;
    ui_Label30 = NULL;
    ui_Container36 = NULL;
    ui_Image11 = NULL;
    ui_Label29 = NULL;
    ui_Container32 = NULL;
    ui_Button2 = NULL;
    ui_Label31 = NULL;
    ui_Label33 = NULL;
    ui_Container34 = NULL;
    ui_Image13 = NULL;
    ui_Label34 = NULL;

}
