// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#ifndef UI_HEALTH_H
#define UI_HEALTH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_health
extern void ui_health_screen_init(void);
extern void ui_health_screen_destroy(void);
extern void ui_event_health(lv_event_t * e);
extern lv_obj_t * ui_health;
extern lv_obj_t * ui_Container31;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Container36;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Container32;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Container34;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Label34;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

