// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#ifndef UI_LAUNCHER_H
#define UI_LAUNCHER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_launcher
extern void ui_launcher_screen_init(void);
extern void ui_launcher_screen_destroy(void);
extern lv_obj_t * ui_launcher;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Container26;
extern lv_obj_t * ui_page1;
extern lv_obj_t * ui_Container2;
extern void ui_event_Image3(lv_event_t * e);
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Container29;
extern void ui_event_Image8(lv_event_t * e);
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Container30;
extern void ui_event_Image10(lv_event_t * e);
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Container47;
extern void ui_event_Image14(lv_event_t * e);
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Container52;
extern void ui_event_Image15(lv_event_t * e);
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_page2;
extern lv_obj_t * ui_Container5;
extern void ui_event_Image6(lv_event_t * e);
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Container61;
extern void ui_event_Image20(lv_event_t * e);
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_page3;
extern lv_obj_t * ui_Container4;
extern void ui_event_Image5(lv_event_t * e);
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label4;
extern void ui_event_volumeslider2(lv_event_t * e);
extern lv_obj_t * ui_volumeslider2;
extern lv_obj_t * ui_Image18;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

