// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#include "../ui.h"

lv_obj_t * ui_launcher = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Container26 = NULL;
lv_obj_t * ui_page1 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Container29 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_Container30 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_Container47 = NULL;
lv_obj_t * ui_Image14 = NULL;
lv_obj_t * ui_Label35 = NULL;
lv_obj_t * ui_Container52 = NULL;
lv_obj_t * ui_Image15 = NULL;
lv_obj_t * ui_Label39 = NULL;
lv_obj_t * ui_page2 = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Container61 = NULL;
lv_obj_t * ui_Image20 = NULL;
lv_obj_t * ui_Label44 = NULL;
lv_obj_t * ui_page3 = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_volumeslider2 = NULL;
lv_obj_t * ui_Image18 = NULL;
// event funtions
void ui_event_Image3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_OVER_LEFT, 300, 0, &ui_Settings_screen_init);
    }
}

void ui_event_Image8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_temp_RH, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 300, 0, &ui_temp_RH_screen_init);
    }
}

void ui_event_Image10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_health, LV_SCR_LOAD_ANIM_OVER_LEFT, 300, 0, &ui_health_screen_init);
    }
}

void ui_event_Image14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_nes_game, LV_SCR_LOAD_ANIM_OVER_LEFT, 300, 0, &ui_nes_game_screen_init);
    }
}

void ui_event_Image15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_file_manager, LV_SCR_LOAD_ANIM_OVER_LEFT, 300, 0, &ui_file_manager_screen_init);
    }
}

void ui_event_Image6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_calculator, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 300, 0, &ui_calculator_screen_init);
    }
}

void ui_event_Image20(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_calendar, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 300, 0, &ui_calendar_screen_init);
    }
}

void ui_event_Image5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_music, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 300, 0, &ui_music_screen_init);
    }
}

void ui_event_volumeslider2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        volume_change(e);
    }
}

// build funtions

void ui_launcher_screen_init(void)
{
    ui_launcher = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_launcher, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                       LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scroll_snap_x(ui_launcher, LV_SCROLL_SNAP_CENTER);

    ui_Image1 = lv_image_create(ui_launcher);
    lv_image_set_src(ui_Image1, &ui_img_launcher_background_png);
    lv_obj_set_width(ui_Image1, lv_pct(100));
    lv_obj_set_height(ui_Image1, lv_pct(100));
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Container26 = lv_obj_create(ui_launcher);
    lv_obj_remove_style_all(ui_Container26);
    lv_obj_set_width(ui_Container26, lv_pct(100));
    lv_obj_set_height(ui_Container26, lv_pct(90));
    lv_obj_set_x(ui_Container26, 0);
    lv_obj_set_y(ui_Container26, lv_pct(10));
    lv_obj_set_flex_flow(ui_Container26, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container26, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container26, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Container26, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_snap_x(ui_Container26, LV_SCROLL_SNAP_START);

    ui_page1 = lv_obj_create(ui_Container26);
    lv_obj_remove_style_all(ui_page1);
    lv_obj_set_width(ui_page1, lv_pct(100));
    lv_obj_set_height(ui_page1, lv_pct(100));
    lv_obj_set_flex_flow(ui_page1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_page1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_page1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_page1, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_style_pad_row(ui_page1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_page1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_page1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_height(ui_Container2, 68);
    lv_obj_set_width(ui_Container2, lv_pct(33));
    lv_obj_set_x(ui_Container2, 10);
    lv_obj_set_y(ui_Container2, 10);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_image_create(ui_Container2);
    lv_image_set_src(ui_Image3, &ui_img_app_settings_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, lv_pct(89));
    lv_obj_set_y(ui_Image3, lv_pct(5));
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_Label1 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "设置");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_page1);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_height(ui_Container3, 68);
    lv_obj_set_width(ui_Container3, lv_pct(33));
    lv_obj_set_x(ui_Container3, 88);
    lv_obj_set_y(ui_Container3, 10);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_image_create(ui_Container3);
    lv_image_set_src(ui_Image4, &ui_img_app_clock_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, lv_pct(89));
    lv_obj_set_y(ui_Image4, lv_pct(5));
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "时钟");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container29 = lv_obj_create(ui_page1);
    lv_obj_remove_style_all(ui_Container29);
    lv_obj_set_height(ui_Container29, 68);
    lv_obj_set_width(ui_Container29, lv_pct(33));
    lv_obj_set_x(ui_Container29, 166);
    lv_obj_set_y(ui_Container29, 10);
    lv_obj_set_flex_flow(ui_Container29, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container29, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container29, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_image_create(ui_Container29);
    lv_image_set_src(ui_Image8, &ui_img_1205787433);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image8, lv_pct(89));
    lv_obj_set_y(ui_Image8, lv_pct(5));
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_Image8, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label26 = lv_label_create(ui_Container29);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "温湿度");
    lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label26, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container30 = lv_obj_create(ui_page1);
    lv_obj_remove_style_all(ui_Container30);
    lv_obj_set_height(ui_Container30, 68);
    lv_obj_set_width(ui_Container30, lv_pct(33));
    lv_obj_set_x(ui_Container30, 10);
    lv_obj_set_y(ui_Container30, 88);
    lv_obj_set_flex_flow(ui_Container30, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container30, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container30, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_image_create(ui_Container30);
    lv_image_set_src(ui_Image10, &ui_img_app_health_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image10, lv_pct(89));
    lv_obj_set_y(ui_Image10, lv_pct(5));
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_Image10, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label27 = lv_label_create(ui_Container30);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "健康");
    lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label27, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container47 = lv_obj_create(ui_page1);
    lv_obj_remove_style_all(ui_Container47);
    lv_obj_set_height(ui_Container47, 68);
    lv_obj_set_width(ui_Container47, lv_pct(33));
    lv_obj_set_x(ui_Container47, 88);
    lv_obj_set_y(ui_Container47, 88);
    lv_obj_set_flex_flow(ui_Container47, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container47, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container47, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image14 = lv_image_create(ui_Container47);
    lv_image_set_src(ui_Image14, &ui_img_app_game_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image14, lv_pct(89));
    lv_obj_set_y(ui_Image14, lv_pct(5));
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_Image14, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label35 = lv_label_create(ui_Container47);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "游戏");
    lv_obj_set_style_text_color(ui_Label35, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label35, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container52 = lv_obj_create(ui_page1);
    lv_obj_remove_style_all(ui_Container52);
    lv_obj_set_height(ui_Container52, 68);
    lv_obj_set_width(ui_Container52, lv_pct(33));
    lv_obj_set_x(ui_Container52, 166);
    lv_obj_set_y(ui_Container52, 88);
    lv_obj_set_flex_flow(ui_Container52, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container52, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container52, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image15 = lv_image_create(ui_Container52);
    lv_image_set_src(ui_Image15, &ui_img_app_file_manager_png);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image15, lv_pct(89));
    lv_obj_set_y(ui_Image15, lv_pct(5));
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_Image15, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label39 = lv_label_create(ui_Container52);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "文件");
    lv_obj_set_style_text_color(ui_Label39, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label39, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2 = lv_obj_create(ui_Container26);
    lv_obj_remove_style_all(ui_page2);
    lv_obj_set_width(ui_page2, lv_pct(100));
    lv_obj_set_height(ui_page2, lv_pct(100));
    lv_obj_set_y(ui_page2, 0);
    lv_obj_set_x(ui_page2, lv_pct(100));
    lv_obj_set_align(ui_page2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_page2, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_page2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_page2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_pad_row(ui_page2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_page2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_page2);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_height(ui_Container5, 68);
    lv_obj_set_width(ui_Container5, lv_pct(33));
    lv_obj_set_x(ui_Container5, 10);
    lv_obj_set_y(ui_Container5, 10);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_image_create(ui_Container5);
    lv_image_set_src(ui_Image6, &ui_img_app_calc_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image6, lv_pct(89));
    lv_obj_set_y(ui_Image6, lv_pct(5));
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_Image6, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags

    ui_Label5 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "计算器");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container61 = lv_obj_create(ui_page2);
    lv_obj_remove_style_all(ui_Container61);
    lv_obj_set_height(ui_Container61, 68);
    lv_obj_set_width(ui_Container61, lv_pct(33));
    lv_obj_set_x(ui_Container61, 10);
    lv_obj_set_y(ui_Container61, 10);
    lv_obj_set_flex_flow(ui_Container61, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container61, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container61, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image20 = lv_image_create(ui_Container61);
    lv_image_set_src(ui_Image20, &ui_img_app_calendar_png);
    lv_obj_set_width(ui_Image20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image20, lv_pct(89));
    lv_obj_set_y(ui_Image20, lv_pct(5));
    lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image20, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_Image20, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags

    ui_Label44 = lv_label_create(ui_Container61);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "日历");
    lv_obj_set_style_text_color(ui_Label44, lv_color_hex(0xFFFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label44, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label44, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page3 = lv_obj_create(ui_Container26);
    lv_obj_remove_style_all(ui_page3);
    lv_obj_set_width(ui_page3, lv_pct(100));
    lv_obj_set_height(ui_page3, lv_pct(100));
    lv_obj_set_y(ui_page3, 0);
    lv_obj_set_x(ui_page3, lv_pct(200));
    lv_obj_set_align(ui_page3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_page3, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_page3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_page3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_pad_row(ui_page3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_page3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_page3);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_height(ui_Container4, 68);
    lv_obj_set_width(ui_Container4, lv_pct(33));
    lv_obj_set_x(ui_Container4, 10);
    lv_obj_set_y(ui_Container4, 10);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_image_create(ui_Container4);
    lv_image_set_src(ui_Image5, &ui_img_app_music_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, lv_pct(89));
    lv_obj_set_y(ui_Image5, lv_pct(5));
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "音乐");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volumeslider2 = lv_slider_create(ui_launcher);
    lv_slider_set_value(ui_volumeslider2, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_volumeslider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_volumeslider2, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_height(ui_volumeslider2, 40);
    lv_obj_set_width(ui_volumeslider2, lv_pct(50));
    lv_obj_set_x(ui_volumeslider2, lv_pct(0));
    lv_obj_set_y(ui_volumeslider2, lv_pct(10));
    lv_obj_set_align(ui_volumeslider2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_volumeslider2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_volumeslider2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_volumeslider2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_volumeslider2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_volumeslider2, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_volumeslider2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_volumeslider2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_volumeslider2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_volumeslider2, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_volumeslider2,
                                                                                                    lv_obj_get_style_pad_right(ui_volumeslider2, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Image18 = lv_image_create(ui_volumeslider2);
    lv_image_set_src(ui_Image18, &ui_img_icon_volume_png);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Image3, ui_event_Image3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image8, ui_event_Image8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image10, ui_event_Image10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image14, ui_event_Image14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image15, ui_event_Image15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image6, ui_event_Image6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image20, ui_event_Image20, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image5, ui_event_Image5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_volumeslider2, ui_event_volumeslider2, LV_EVENT_ALL, NULL);

}

void ui_launcher_screen_destroy(void)
{
    if(ui_launcher) lv_obj_del(ui_launcher);

    // NULL screen variables
    ui_launcher = NULL;
    ui_Image1 = NULL;
    ui_Container26 = NULL;
    ui_page1 = NULL;
    ui_Container2 = NULL;
    ui_Image3 = NULL;
    ui_Label1 = NULL;
    ui_Container3 = NULL;
    ui_Image4 = NULL;
    ui_Label3 = NULL;
    ui_Container29 = NULL;
    ui_Image8 = NULL;
    ui_Label26 = NULL;
    ui_Container30 = NULL;
    ui_Image10 = NULL;
    ui_Label27 = NULL;
    ui_Container47 = NULL;
    ui_Image14 = NULL;
    ui_Label35 = NULL;
    ui_Container52 = NULL;
    ui_Image15 = NULL;
    ui_Label39 = NULL;
    ui_page2 = NULL;
    ui_Container5 = NULL;
    ui_Image6 = NULL;
    ui_Label5 = NULL;
    ui_Container61 = NULL;
    ui_Image20 = NULL;
    ui_Label44 = NULL;
    ui_page3 = NULL;
    ui_Container4 = NULL;
    ui_Image5 = NULL;
    ui_Label4 = NULL;
    ui_volumeslider2 = NULL;
    ui_Image18 = NULL;

}
