// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#ifndef UI_MUSIC_H
#define UI_MUSIC_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_music
extern void ui_music_screen_init(void);
extern void ui_music_screen_destroy(void);
extern void ui_event_music(lv_event_t * e);
extern lv_obj_t * ui_music;
extern lv_obj_t * ui_Container74;
extern lv_obj_t * ui_Container73;
extern lv_obj_t * ui_Container42;
extern lv_obj_t * ui_musci_changpian;
extern lv_obj_t * ui_music_info_label;
extern lv_obj_t * ui_Container39;
extern lv_obj_t * ui_Container40;
extern lv_obj_t * ui_music_cur_time;
extern lv_obj_t * ui_Container41;
extern lv_obj_t * ui_music_duration;
extern void ui_event_music_seek(lv_event_t * e);
extern lv_obj_t * ui_music_seek;
extern lv_obj_t * ui_Container33;
extern lv_obj_t * ui_Container35;
extern void ui_event_skip_back(lv_event_t * e);
extern lv_obj_t * ui_skip_back;
extern lv_obj_t * ui_Container37;
extern void ui_event_play(lv_event_t * e);
extern lv_obj_t * ui_play;
extern void ui_event_pause(lv_event_t * e);
extern lv_obj_t * ui_pause;
extern lv_obj_t * ui_Container38;
extern void ui_event_skip_forward(lv_event_t * e);
extern lv_obj_t * ui_skip_forward;
extern lv_obj_t * ui_Container43;
extern lv_obj_t * ui_Container46;
extern lv_obj_t * ui_Label32;
extern void ui_event_music_refresh(lv_event_t * e);
extern lv_obj_t * ui_music_refresh;
extern lv_obj_t * ui_Container45;
extern lv_obj_t * ui_simpleitem2;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_simple_item_text1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

