// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#include "../ui.h"

lv_obj_t * ui_music = NULL;
lv_obj_t * ui_Container74 = NULL;
lv_obj_t * ui_Container73 = NULL;
lv_obj_t * ui_Container42 = NULL;
lv_obj_t * ui_musci_changpian = NULL;
lv_obj_t * ui_music_info_label = NULL;
lv_obj_t * ui_Container39 = NULL;
lv_obj_t * ui_Container40 = NULL;
lv_obj_t * ui_music_cur_time = NULL;
lv_obj_t * ui_Container41 = NULL;
lv_obj_t * ui_music_duration = NULL;
lv_obj_t * ui_music_seek = NULL;
lv_obj_t * ui_Container33 = NULL;
lv_obj_t * ui_Container35 = NULL;
lv_obj_t * ui_skip_back = NULL;
lv_obj_t * ui_Container37 = NULL;
lv_obj_t * ui_play = NULL;
lv_obj_t * ui_pause = NULL;
lv_obj_t * ui_Container38 = NULL;
lv_obj_t * ui_skip_forward = NULL;
lv_obj_t * ui_Container43 = NULL;
lv_obj_t * ui_Container46 = NULL;
lv_obj_t * ui_Label32 = NULL;
lv_obj_t * ui_music_refresh = NULL;
lv_obj_t * ui_Container45 = NULL;
lv_obj_t * ui_simpleitem2 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_simple_item_text1 = NULL;
// event funtions
void ui_event_music(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        music_loaded(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        music_unloaded(e);
    }
}

void ui_event_music_seek(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        music_seek_released(e);
    }
    if(event_code == LV_EVENT_PRESSED) {
        music_seek_pressed(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        music_seek_value_changed(e);
    }
}

void ui_event_skip_back(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        music_action(e);
    }
}

void ui_event_play(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        music_action(e);
    }
}

void ui_event_pause(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        music_action(e);
    }
}

void ui_event_skip_forward(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        music_action(e);
    }
}

void ui_event_music_refresh(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        music_list_refresh(e);
    }
}

// build funtions

void ui_music_screen_init(void)
{
    ui_music = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(ui_music, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_snap_x(ui_music, LV_SCROLL_SNAP_START);
    lv_obj_set_flex_flow(ui_music, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_music, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_Container74 = lv_obj_create(ui_music);
    lv_obj_remove_style_all(ui_Container74);
    lv_obj_set_height(ui_Container74, 25);
    lv_obj_set_width(ui_Container74, lv_pct(100));
    lv_obj_set_align(ui_Container74, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container74, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container74, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container74, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container73 = lv_obj_create(ui_music);
    lv_obj_remove_style_all(ui_Container73);
    lv_obj_set_width(ui_Container73, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container73, 1);
    lv_obj_set_align(ui_Container73, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container73, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container73, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_scroll_snap_x(ui_Container73, LV_SCROLL_SNAP_START);
    lv_obj_set_style_bg_color(ui_Container73, lv_color_hex(0x3D3D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container73, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container42 = lv_obj_create(ui_Container73);
    lv_obj_remove_style_all(ui_Container42);
    lv_obj_set_width(ui_Container42, lv_pct(100));
    lv_obj_set_height(ui_Container42, lv_pct(100));
    lv_obj_remove_flag(ui_Container42, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scroll_snap_x(ui_Container42, LV_SCROLL_SNAP_CENTER);

    ui_musci_changpian = lv_image_create(ui_Container42);
    lv_image_set_src(ui_musci_changpian, &ui_img_music_changpian_png);
    lv_obj_set_width(ui_musci_changpian, 120);
    lv_obj_set_height(ui_musci_changpian, 120);
    lv_obj_set_x(ui_musci_changpian, 0);
    lv_obj_set_y(ui_musci_changpian, lv_pct(5));
    lv_obj_set_align(ui_musci_changpian, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_musci_changpian, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_musci_changpian, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_musci_changpian, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_musci_changpian, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_music_info_label = lv_label_create(ui_Container42);
    lv_obj_set_width(ui_music_info_label, lv_pct(100));
    lv_obj_set_height(ui_music_info_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_music_info_label, 0);
    lv_obj_set_y(ui_music_info_label, lv_pct(50));
    lv_obj_set_align(ui_music_info_label, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_music_info_label, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_music_info_label, "");
    lv_obj_set_style_text_color(ui_music_info_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_music_info_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_music_info_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_music_info_label, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container39 = lv_obj_create(ui_Container42);
    lv_obj_remove_style_all(ui_Container39);
    lv_obj_set_height(ui_Container39, 20);
    lv_obj_set_width(ui_Container39, lv_pct(80));
    lv_obj_set_x(ui_Container39, 0);
    lv_obj_set_y(ui_Container39, lv_pct(65));
    lv_obj_set_align(ui_Container39, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Container39, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container39, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container39, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container40 = lv_obj_create(ui_Container39);
    lv_obj_remove_style_all(ui_Container40);
    lv_obj_set_height(ui_Container40, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_flex_grow(ui_Container40, 1);
    lv_obj_set_align(ui_Container40, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container40, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_music_cur_time = lv_label_create(ui_Container40);
    lv_obj_set_width(ui_music_cur_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_music_cur_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_music_cur_time, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_music_cur_time, "00:00");
    lv_obj_set_style_text_color(ui_music_cur_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_music_cur_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container41 = lv_obj_create(ui_Container39);
    lv_obj_remove_style_all(ui_Container41);
    lv_obj_set_height(ui_Container41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Container41, 1);
    lv_obj_set_align(ui_Container41, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container41, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_music_duration = lv_label_create(ui_Container41);
    lv_obj_set_width(ui_music_duration, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_music_duration, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_music_duration, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_music_duration, "00:00");
    lv_obj_set_style_text_color(ui_music_duration, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_music_duration, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_music_seek = lv_slider_create(ui_Container42);
    lv_slider_set_value(ui_music_seek, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_music_seek) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_music_seek, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_music_seek, 10);
    lv_obj_set_width(ui_music_seek, lv_pct(80));
    lv_obj_set_x(ui_music_seek, 0);
    lv_obj_set_y(ui_music_seek, lv_pct(60));
    lv_obj_set_align(ui_music_seek, LV_ALIGN_TOP_MID);
    lv_obj_set_ext_click_area(ui_music_seek, 10);
    lv_obj_remove_flag(ui_music_seek, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_music_seek, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_music_seek, lv_color_hex(0xFFFF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_music_seek, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_music_seek, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_music_seek, lv_color_hex(0x00FF00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_music_seek, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_music_seek, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_music_seek, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_music_seek, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_music_seek, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_music_seek, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_music_seek,
                                                                                                 lv_obj_get_style_pad_right(ui_music_seek, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Container33 = lv_obj_create(ui_Container42);
    lv_obj_remove_style_all(ui_Container33);
    lv_obj_set_height(ui_Container33, 50);
    lv_obj_set_width(ui_Container33, lv_pct(100));
    lv_obj_set_x(ui_Container33, 0);
    lv_obj_set_y(ui_Container33, lv_pct(75));
    lv_obj_set_align(ui_Container33, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Container33, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container33, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container33, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container35 = lv_obj_create(ui_Container33);
    lv_obj_remove_style_all(ui_Container35);
    lv_obj_set_height(ui_Container35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Container35, 1);
    lv_obj_set_x(ui_Container35, -63);
    lv_obj_set_y(ui_Container35, -1);
    lv_obj_set_align(ui_Container35, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container35, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_skip_back = lv_image_create(ui_Container35);
    lv_image_set_src(ui_skip_back, &ui_img_1330499080);
    lv_obj_set_width(ui_skip_back, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_skip_back, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_skip_back, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(ui_skip_back, 10);
    lv_obj_add_flag(ui_skip_back, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_skip_back, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container37 = lv_obj_create(ui_Container33);
    lv_obj_remove_style_all(ui_Container37);
    lv_obj_set_height(ui_Container37, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_flex_grow(ui_Container37, 1);
    lv_obj_set_x(ui_Container37, 32);
    lv_obj_set_y(ui_Container37, -7);
    lv_obj_set_align(ui_Container37, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container37, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_play = lv_image_create(ui_Container37);
    lv_image_set_src(ui_play, &ui_img_play_png);
    lv_obj_set_width(ui_play, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_play, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_play, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(ui_play, 10);
    lv_obj_add_state(ui_play, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_play, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_play, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_play, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_play, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_play, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_play, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_play, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_play, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_play, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pause = lv_image_create(ui_Container37);
    lv_image_set_src(ui_pause, &ui_img_pause_png);
    lv_obj_set_width(ui_pause, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pause, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_pause, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(ui_pause, 10);
    lv_obj_add_state(ui_pause, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_pause, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_pause, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pause, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pause, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pause, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pause, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pause, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pause, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pause, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container38 = lv_obj_create(ui_Container33);
    lv_obj_remove_style_all(ui_Container38);
    lv_obj_set_height(ui_Container38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Container38, 1);
    lv_obj_set_x(ui_Container38, 68);
    lv_obj_set_y(ui_Container38, 26);
    lv_obj_set_align(ui_Container38, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container38, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_skip_forward = lv_image_create(ui_Container38);
    lv_image_set_src(ui_skip_forward, &ui_img_1259189730);
    lv_obj_set_width(ui_skip_forward, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_skip_forward, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_skip_forward, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(ui_skip_forward, 10);
    lv_obj_add_flag(ui_skip_forward, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_skip_forward, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container43 = lv_obj_create(ui_Container73);
    lv_obj_remove_style_all(ui_Container43);
    lv_obj_set_width(ui_Container43, lv_pct(100));
    lv_obj_set_height(ui_Container43, lv_pct(100));
    lv_obj_set_y(ui_Container43, 0);
    lv_obj_set_x(ui_Container43, lv_pct(100));
    lv_obj_set_align(ui_Container43, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container43, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scroll_snap_x(ui_Container43, LV_SCROLL_SNAP_CENTER);

    ui_Container46 = lv_obj_create(ui_Container43);
    lv_obj_remove_style_all(ui_Container46);
    lv_obj_set_width(ui_Container46, lv_pct(100));
    lv_obj_set_height(ui_Container46, lv_pct(15));
    lv_obj_set_flex_flow(ui_Container46, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container46, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container46, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container46, lv_color_hex(0x777777), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container46, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_Container46);
    lv_obj_set_width(ui_Label32, lv_pct(40));
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label32, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label32, "歌曲列表");
    lv_obj_set_style_text_color(ui_Label32, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label32, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label32, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_music_refresh = lv_image_create(ui_Container46);
    lv_image_set_src(ui_music_refresh, &ui_img_icon_refresh_png);
    lv_obj_set_width(ui_music_refresh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_music_refresh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_music_refresh, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(ui_music_refresh, 5);
    lv_obj_add_flag(ui_music_refresh, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_music_refresh,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                       LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_music_refresh, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_music_refresh, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_music_refresh, 128, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_pad_left(ui_music_refresh, 1, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_pad_right(ui_music_refresh, 1, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_pad_top(ui_music_refresh, 1, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_pad_bottom(ui_music_refresh, 1, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Container45 = lv_obj_create(ui_Container43);
    lv_obj_remove_style_all(ui_Container45);
    lv_obj_set_width(ui_Container45, lv_pct(100));
    lv_obj_set_height(ui_Container45, lv_pct(85));
    lv_obj_set_x(ui_Container45, lv_pct(0));
    lv_obj_set_y(ui_Container45, lv_pct(15));
    lv_obj_remove_flag(ui_Container45, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_simpleitem2 = lv_obj_create(ui_Container45);
    lv_obj_remove_style_all(ui_simpleitem2);
    lv_obj_set_height(ui_simpleitem2, 50);
    lv_obj_set_width(ui_simpleitem2, lv_pct(95));
    lv_obj_set_align(ui_simpleitem2, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_simpleitem2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_simpleitem2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_simpleitem2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_simpleitem2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_simpleitem2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_simpleitem2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_simpleitem2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_simpleitem2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_simpleitem2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_simpleitem2, 20, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Image12 = lv_image_create(ui_simpleitem2);
    lv_image_set_src(ui_Image12, &ui_img_item_music_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image12, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_simple_item_text1 = lv_label_create(ui_simpleitem2);
    lv_obj_set_height(ui_simple_item_text1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_simple_item_text1, 1);
    lv_obj_set_x(ui_simple_item_text1, 32);
    lv_obj_set_y(ui_simple_item_text1, 0);
    lv_obj_set_align(ui_simple_item_text1, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_simple_item_text1, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_simple_item_text1, "");
    lv_obj_set_style_text_color(ui_simple_item_text1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_simple_item_text1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_simple_item_text1, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_simple_item_text1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_simple_item_text1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_simple_item_text1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_simple_item_text1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_music_seek, ui_event_music_seek, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_skip_back, ui_event_skip_back, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_play, ui_event_play, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pause, ui_event_pause, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_skip_forward, ui_event_skip_forward, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_music_refresh, ui_event_music_refresh, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_music, ui_event_music, LV_EVENT_ALL, NULL);

}

void ui_music_screen_destroy(void)
{
    if(ui_music) lv_obj_del(ui_music);

    // NULL screen variables
    ui_music = NULL;
    ui_Container74 = NULL;
    ui_Container73 = NULL;
    ui_Container42 = NULL;
    ui_musci_changpian = NULL;
    ui_music_info_label = NULL;
    ui_Container39 = NULL;
    ui_Container40 = NULL;
    ui_music_cur_time = NULL;
    ui_Container41 = NULL;
    ui_music_duration = NULL;
    ui_music_seek = NULL;
    ui_Container33 = NULL;
    ui_Container35 = NULL;
    ui_skip_back = NULL;
    ui_Container37 = NULL;
    ui_play = NULL;
    ui_pause = NULL;
    ui_Container38 = NULL;
    ui_skip_forward = NULL;
    ui_Container43 = NULL;
    ui_Container46 = NULL;
    ui_Label32 = NULL;
    ui_music_refresh = NULL;
    ui_Container45 = NULL;
    ui_simpleitem2 = NULL;
    ui_Image12 = NULL;
    ui_simple_item_text1 = NULL;

}
