// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#include "../ui.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

lv_obj_t * ui_music = NULL;
lv_obj_t * ui_Container74 = NULL;
lv_obj_t * ui_Container73 = NULL;

// 歌词页面句柄
lv_obj_t * ui_Container_lrc = NULL;
lv_obj_t * ui_lrc_list = NULL;

lv_obj_t * ui_Container42 = NULL;
lv_obj_t * ui_musci_changpian = NULL;
lv_obj_t * ui_music_info_label = NULL;
lv_obj_t * ui_Container39 = NULL;
lv_obj_t * ui_Container40 = NULL;
lv_obj_t * ui_music_cur_time = NULL;
lv_obj_t * ui_Container41 = NULL;
lv_obj_t * ui_music_duration = NULL;
lv_obj_t * ui_music_seek = NULL;
lv_obj_t * ui_Container33 = NULL;
lv_obj_t * ui_Container35 = NULL;
lv_obj_t * ui_skip_back = NULL;
lv_obj_t * ui_Container37 = NULL;
lv_obj_t * ui_play = NULL;
lv_obj_t * ui_pause = NULL;
lv_obj_t * ui_Container38 = NULL;
lv_obj_t * ui_skip_forward = NULL;
lv_obj_t * ui_Container43 = NULL;
lv_obj_t * ui_Container46 = NULL;
lv_obj_t * ui_Label32 = NULL;
lv_obj_t * ui_music_refresh = NULL;
lv_obj_t * ui_Container45 = NULL;
lv_obj_t * ui_simpleitem2 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_simple_item_text1 = NULL;

#define MAX_LRC_LINES 250

static lrc_line_t g_lrc_lines[MAX_LRC_LINES];
static lv_obj_t*  g_lrc_labels[MAX_LRC_LINES];
static int        g_lrc_count = 0;
static int        g_current_index = -1;

// event funtions
void ui_event_music(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        music_loaded(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        music_unloaded(e);
    }
}

void ui_event_music_seek(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        music_seek_released(e);
    }
    if(event_code == LV_EVENT_PRESSED) {
        music_seek_pressed(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        music_seek_value_changed(e);
    }
}

void ui_event_skip_back(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        music_action(e);
    }
}

void ui_event_play(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        music_action(e);
    }
}

void ui_event_pause(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        music_action(e);
    }
}

void ui_event_skip_forward(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        music_action(e);
    }
}

void ui_event_music_refresh(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        music_list_refresh(e);
    }
}

// build funtions

void ui_music_screen_init(void)
{
    ui_music = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(ui_music, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_snap_x(ui_music, LV_SCROLL_SNAP_START);
    lv_obj_set_flex_flow(ui_music, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_music, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_Container74 = lv_obj_create(ui_music);
    lv_obj_remove_style_all(ui_Container74);
    lv_obj_set_height(ui_Container74, 25);
    lv_obj_set_width(ui_Container74, lv_pct(100));
    lv_obj_set_align(ui_Container74, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container74, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container74, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container74, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container73 = lv_obj_create(ui_music);
    lv_obj_remove_style_all(ui_Container73);
    lv_obj_set_width(ui_Container73, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container73, 1);
    lv_obj_set_align(ui_Container73, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container73, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container73, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    
    // 水平单页切页设置，防连滑透传
    lv_obj_set_scroll_dir(ui_Container73, LV_DIR_HOR);
    lv_obj_add_flag(ui_Container73, LV_OBJ_FLAG_SCROLL_ONE);
    lv_obj_remove_flag(ui_Container73, LV_OBJ_FLAG_SCROLL_MOMENTUM);
    lv_obj_set_scroll_snap_x(ui_Container73, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_scrollbar_mode(ui_Container73, LV_SCROLLBAR_MODE_OFF);
    
    lv_obj_set_style_bg_color(ui_Container73, lv_color_hex(0x3D3D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container73, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* ================= PAGE 1 (左侧): 歌词页面 ================= */
    ui_Container_lrc = lv_obj_create(ui_Container73);
    lv_obj_remove_style_all(ui_Container_lrc);
    lv_obj_set_width(ui_Container_lrc, lv_pct(100));
    lv_obj_set_height(ui_Container_lrc, lv_pct(100));
    lv_obj_set_align(ui_Container_lrc, LV_ALIGN_CENTER);
    lv_obj_set_scroll_snap_x(ui_Container_lrc, LV_SCROLL_SNAP_CENTER);

    ui_lrc_list = lv_obj_create(ui_Container_lrc);
    lv_obj_set_width(ui_lrc_list, lv_pct(100));
    lv_obj_set_height(ui_lrc_list, lv_pct(100));
    lv_obj_set_align(ui_lrc_list, LV_ALIGN_CENTER);
    
    // 歌词只垂直滚动，水平拖动向上透传给 Container73 切页
    lv_obj_set_scroll_dir(ui_lrc_list, LV_DIR_VER);
    lv_obj_add_flag(ui_lrc_list, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_GESTURE_BUBBLE);
    lv_obj_set_scrollbar_mode(ui_lrc_list, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_flex_flow(ui_lrc_list, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_lrc_list, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    
    lv_obj_set_style_bg_opa(ui_lrc_list, 0, LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_lrc_list, 0, LV_PART_MAIN);
    lv_obj_set_style_pad_top(ui_lrc_list, 110, LV_PART_MAIN);
    lv_obj_set_style_pad_bottom(ui_lrc_list, 110, LV_PART_MAIN);
    lv_obj_set_style_pad_row(ui_lrc_list, 12, LV_PART_MAIN);

    /* ================= PAGE 2 (中间): 唱片与控制界面 ================= */
    ui_Container42 = lv_obj_create(ui_Container73);
    lv_obj_remove_style_all(ui_Container42);
    lv_obj_set_width(ui_Container42, lv_pct(100));
    lv_obj_set_height(ui_Container42, lv_pct(100));
    lv_obj_remove_flag(ui_Container42, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scroll_snap_x(ui_Container42, LV_SCROLL_SNAP_CENTER);

    ui_musci_changpian = lv_image_create(ui_Container42);
    lv_image_set_src(ui_musci_changpian, &ui_img_music_changpian_png);
    lv_obj_set_width(ui_musci_changpian, 120);
    lv_obj_set_height(ui_musci_changpian, 120);
    lv_obj_set_x(ui_musci_changpian, 0);
    lv_obj_set_y(ui_musci_changpian, lv_pct(5));
    lv_obj_set_align(ui_musci_changpian, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_musci_changpian, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_musci_changpian, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_musci_changpian, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_musci_changpian, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_music_info_label = lv_label_create(ui_Container42);
    lv_obj_set_width(ui_music_info_label, lv_pct(100));
    lv_obj_set_height(ui_music_info_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_music_info_label, 0);
    lv_obj_set_y(ui_music_info_label, lv_pct(50));
    lv_obj_set_align(ui_music_info_label, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_music_info_label, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_music_info_label, "");
    lv_obj_set_style_text_color(ui_music_info_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_music_info_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_music_info_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_music_info_label, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container39 = lv_obj_create(ui_Container42);
    lv_obj_remove_style_all(ui_Container39);
    lv_obj_set_height(ui_Container39, 20);
    lv_obj_set_width(ui_Container39, lv_pct(80));
    lv_obj_set_x(ui_Container39, 0);
    lv_obj_set_y(ui_Container39, lv_pct(65));
    lv_obj_set_align(ui_Container39, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Container39, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container39, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container39, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container40 = lv_obj_create(ui_Container39);
    lv_obj_remove_style_all(ui_Container40);
    lv_obj_set_height(ui_Container40, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_flex_grow(ui_Container40, 1);
    lv_obj_set_align(ui_Container40, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container40, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_music_cur_time = lv_label_create(ui_Container40);
    lv_obj_set_width(ui_music_cur_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_music_cur_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_music_cur_time, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_music_cur_time, "00:00");
    lv_obj_set_style_text_color(ui_music_cur_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_music_cur_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container41 = lv_obj_create(ui_Container39);
    lv_obj_remove_style_all(ui_Container41);
    lv_obj_set_height(ui_Container41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Container41, 1);
    lv_obj_set_align(ui_Container41, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container41, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_music_duration = lv_label_create(ui_Container41);
    lv_obj_set_width(ui_music_duration, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_music_duration, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_music_duration, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_music_duration, "00:00");
    lv_obj_set_style_text_color(ui_music_duration, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_music_duration, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_music_seek = lv_slider_create(ui_Container42);
    lv_slider_set_value(ui_music_seek, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_music_seek) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_music_seek, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_music_seek, 10);
    lv_obj_set_width(ui_music_seek, lv_pct(80));
    lv_obj_set_x(ui_music_seek, 0);
    lv_obj_set_y(ui_music_seek, lv_pct(60));
    lv_obj_set_align(ui_music_seek, LV_ALIGN_TOP_MID);
    lv_obj_set_ext_click_area(ui_music_seek, 10);
    lv_obj_remove_flag(ui_music_seek, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_music_seek, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_music_seek, lv_color_hex(0xFFFF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_music_seek, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_music_seek, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_music_seek, lv_color_hex(0x00FF00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_music_seek, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_music_seek, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_music_seek, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_music_seek, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_music_seek, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    if(lv_obj_get_style_pad_top(ui_music_seek, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_music_seek,
                                                                                                 lv_obj_get_style_pad_right(ui_music_seek, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Container33 = lv_obj_create(ui_Container42);
    lv_obj_remove_style_all(ui_Container33);
    lv_obj_set_height(ui_Container33, 50);
    lv_obj_set_width(ui_Container33, lv_pct(100));
    lv_obj_set_x(ui_Container33, 0);
    lv_obj_set_y(ui_Container33, lv_pct(75));
    lv_obj_set_align(ui_Container33, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Container33, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container33, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container33, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container35 = lv_obj_create(ui_Container33);
    lv_obj_remove_style_all(ui_Container35);
    lv_obj_set_height(ui_Container35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Container35, 1);
    lv_obj_set_x(ui_Container35, -63);
    lv_obj_set_y(ui_Container35, -1);
    lv_obj_set_align(ui_Container35, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container35, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_skip_back = lv_image_create(ui_Container35);
    lv_image_set_src(ui_skip_back, &ui_img_1330499080);
    lv_obj_set_width(ui_skip_back, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_skip_back, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_skip_back, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(ui_skip_back, 10);
    lv_obj_add_flag(ui_skip_back, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_skip_back, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container37 = lv_obj_create(ui_Container33);
    lv_obj_remove_style_all(ui_Container37);
    lv_obj_set_height(ui_Container37, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_flex_grow(ui_Container37, 1);
    lv_obj_set_x(ui_Container37, 32);
    lv_obj_set_y(ui_Container37, -7);
    lv_obj_set_align(ui_Container37, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container37, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_play = lv_image_create(ui_Container37);
    lv_image_set_src(ui_play, &ui_img_play_png);
    lv_obj_set_width(ui_play, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_play, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_play, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(ui_play, 10);
    lv_obj_add_state(ui_play, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_play, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_play, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_play, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_play, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_play, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_play, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_play, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_play, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_play, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pause = lv_image_create(ui_Container37);
    lv_image_set_src(ui_pause, &ui_img_pause_png);
    lv_obj_set_width(ui_pause, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pause, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_pause, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(ui_pause, 10);
    lv_obj_add_state(ui_pause, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_pause, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_pause, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pause, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pause, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pause, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pause, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pause, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pause, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pause, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container38 = lv_obj_create(ui_Container33);
    lv_obj_remove_style_all(ui_Container38);
    lv_obj_set_height(ui_Container38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Container38, 1);
    lv_obj_set_x(ui_Container38, 68);
    lv_obj_set_y(ui_Container38, 26);
    lv_obj_set_align(ui_Container38, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container38, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_skip_forward = lv_image_create(ui_Container38);
    lv_image_set_src(ui_skip_forward, &ui_img_1259189730);
    lv_obj_set_width(ui_skip_forward, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_skip_forward, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_skip_forward, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(ui_skip_forward, 10);
    lv_obj_add_flag(ui_skip_forward, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_skip_forward, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    /* ================= PAGE 3 (右侧): 歌曲列表 ================= */
    ui_Container43 = lv_obj_create(ui_Container73);
    lv_obj_remove_style_all(ui_Container43);
    lv_obj_set_width(ui_Container43, lv_pct(100));
    lv_obj_set_height(ui_Container43, lv_pct(100));
    lv_obj_set_y(ui_Container43, 0);
    lv_obj_set_x(ui_Container43, lv_pct(100));
    lv_obj_set_align(ui_Container43, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container43, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scroll_snap_x(ui_Container43, LV_SCROLL_SNAP_CENTER);

    ui_Container46 = lv_obj_create(ui_Container43);
    lv_obj_remove_style_all(ui_Container46);
    lv_obj_set_width(ui_Container46, lv_pct(100));
    lv_obj_set_height(ui_Container46, lv_pct(15));
    lv_obj_set_flex_flow(ui_Container46, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container46, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container46, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container46, lv_color_hex(0x777777), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container46, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_Container46);
    lv_obj_set_width(ui_Label32, lv_pct(40));
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label32, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label32, "歌曲列表");
    lv_obj_set_style_text_color(ui_Label32, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label32, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label32, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_music_refresh = lv_image_create(ui_Container46);
    lv_image_set_src(ui_music_refresh, &ui_img_icon_refresh_png);
    lv_obj_set_width(ui_music_refresh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_music_refresh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_music_refresh, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(ui_music_refresh, 5);
    lv_obj_add_flag(ui_music_refresh, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_music_refresh,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                       LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_music_refresh, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_music_refresh, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_music_refresh, 128, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_pad_left(ui_music_refresh, 1, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_pad_right(ui_music_refresh, 1, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_pad_top(ui_music_refresh, 1, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_pad_bottom(ui_music_refresh, 1, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Container45 = lv_obj_create(ui_Container43);
    lv_obj_remove_style_all(ui_Container45);
    lv_obj_set_width(ui_Container45, lv_pct(100));
    lv_obj_set_height(ui_Container45, lv_pct(85));
    lv_obj_set_x(ui_Container45, lv_pct(0));
    lv_obj_set_y(ui_Container45, lv_pct(15));
    
    // 列表垂直滑动并开启透传
    lv_obj_set_scroll_dir(ui_Container45, LV_DIR_VER);
    lv_obj_add_flag(ui_Container45, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_GESTURE_BUBBLE);
    lv_obj_set_scrollbar_mode(ui_Container45, LV_SCROLLBAR_MODE_AUTO);
    lv_obj_set_flex_flow(ui_Container45, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container45, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    // 初始卡位居中放在播放控制器页
    lv_obj_scroll_to_view(ui_Container42, LV_ANIM_OFF);

    // 默认显示美化的“暂无歌词”
    lrc_clear();

    lv_obj_add_event_cb(ui_music_seek, ui_event_music_seek, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_skip_back, ui_event_skip_back, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_play, ui_event_play, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pause, ui_event_pause, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_skip_forward, ui_event_skip_forward, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_music_refresh, ui_event_music_refresh, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_music, ui_event_music, LV_EVENT_ALL, NULL);
}

void ui_music_screen_destroy(void)
{
    lrc_clear();

    if(ui_music) lv_obj_del(ui_music);

    ui_music = NULL;
    ui_Container74 = NULL;
    ui_Container73 = NULL;

    ui_Container_lrc = NULL;
    ui_lrc_list = NULL;

    ui_Container42 = NULL;
    ui_musci_changpian = NULL;
    ui_music_info_label = NULL;
    ui_Container39 = NULL;
    ui_Container40 = NULL;
    ui_music_cur_time = NULL;
    ui_Container41 = NULL;
    ui_music_duration = NULL;
    ui_music_seek = NULL;
    ui_Container33 = NULL;
    ui_Container35 = NULL;
    ui_skip_back = NULL;
    ui_Container37 = NULL;
    ui_play = NULL;
    ui_pause = NULL;
    ui_Container38 = NULL;
    ui_skip_forward = NULL;
    ui_Container43 = NULL;
    ui_Container46 = NULL;
    ui_Label32 = NULL;
    ui_music_refresh = NULL;
    ui_Container45 = NULL;
    ui_simpleitem2 = NULL;
    ui_Image12 = NULL;
    ui_simple_item_text1 = NULL;
}

/* ================= 歌词接口与逻辑函数 ================= */

void lrc_clear(void)
{
    if (ui_lrc_list) {
        lv_obj_clean(ui_lrc_list);
    }
    for (int i = 0; i < g_lrc_count; i++) {
        if (g_lrc_lines[i].text) {
            free(g_lrc_lines[i].text);
            g_lrc_lines[i].text = NULL;
        }
        g_lrc_labels[i] = NULL;
    }
    g_lrc_count = 0;
    g_current_index = -1;

    // 清空时自动居中放置美化的“暂无歌词”
    if (ui_lrc_list) {
        lv_obj_t * empty_label = lv_label_create(ui_lrc_list);
        lv_label_set_text(empty_label, "暂无歌词");
        lv_obj_set_width(empty_label, lv_pct(100));
        lv_obj_set_style_text_align(empty_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);
        lv_obj_set_style_text_font(empty_label, &ui_font_simhei14, LV_PART_MAIN);
        lv_obj_set_style_text_color(empty_label, lv_color_hex(0x888888), LV_PART_MAIN);
        lv_obj_set_style_text_opa(empty_label, 150, LV_PART_MAIN);
    }
}

static int compare_lrc(const void *a, const void *b)
{
    const lrc_line_t *la = (const lrc_line_t *)a;
    const lrc_line_t *lb = (const lrc_line_t *)b;
    return (la->time_ms > lb->time_ms) - (la->time_ms < lb->time_ms);
}

bool lrc_parse(const char *lrc_str)
{
    lrc_clear();
    if (!lrc_str || !ui_lrc_list) return false;

    const char *line = lrc_str;
    while (*line && g_lrc_count < MAX_LRC_LINES) {
        int m = 0, s = 0, ms = 0;
        if (sscanf(line, "[%d:%d.%d]", &m, &s, &ms) == 3 || sscanf(line, "[%d:%d:%d]", &m, &s, &ms) == 3) {
            const char *text_start = strchr(line, ']');
            if (text_start) {
                text_start++;
                const char *next_line = strchr(line, '\n');
                int len = next_line ? (next_line - text_start) : (int)strlen(text_start);

                if (len > 0 && text_start[len - 1] == '\r') len--;

                if (len > 0) {
                    g_lrc_lines[g_lrc_count].time_ms = (m * 60 + s) * 1000 + ms * 10;
                    g_lrc_lines[g_lrc_count].text = (char *)malloc(len + 1);
                    if (g_lrc_lines[g_lrc_count].text) {
                        strncpy(g_lrc_lines[g_lrc_count].text, text_start, len);
                        g_lrc_lines[g_lrc_count].text[len] = '\0';
                        g_lrc_count++;
                    }
                }
            }
        }
        line = strchr(line, '\n');
        if (!line) break;
        line++;
    }

    if (g_lrc_count == 0) return false;

    // 清除“暂无歌词”控件
    lv_obj_clean(ui_lrc_list);

    qsort(g_lrc_lines, g_lrc_count, sizeof(lrc_line_t), compare_lrc);

    for (int i = 0; i < g_lrc_count; i++) {
        g_lrc_labels[i] = lv_label_create(ui_lrc_list);
        lv_label_set_text(g_lrc_labels[i], g_lrc_lines[i].text);
        lv_obj_set_width(g_lrc_labels[i], lv_pct(90));
        lv_obj_set_style_text_align(g_lrc_labels[i], LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);
        lv_obj_set_style_text_font(g_lrc_labels[i], &ui_font_simhei14, LV_PART_MAIN);

        // 普通行样式
        lv_obj_set_style_text_color(g_lrc_labels[i], lv_color_hex(0x888888), LV_PART_MAIN);
        lv_obj_set_style_text_opa(g_lrc_labels[i], 160, LV_PART_MAIN);
    }

    return true;
}

bool lrc_parse_file(const char *file_path)
{
    if (!file_path) return false;

    FILE *f = fopen(file_path, "rb");
    if (!f) {
        lrc_clear();
        return false;
    }

    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);

    if (size <= 0) {
        fclose(f);
        lrc_clear();
        return false;
    }

    char *buf = (char *)malloc(size + 1);
    if (!buf) {
        fclose(f);
        lrc_clear();
        return false;
    }

    fread(buf, 1, size, f);
    buf[size] = '\0';
    fclose(f);

    bool res = lrc_parse(buf);
    free(buf);
    return res;
}

// 自动把后缀名替换为 .lrc 并加载歌词
bool lrc_parse_by_audio_path(const char *audio_path)
{
    if (!audio_path) return false;

    size_t len = strlen(audio_path);
    char *lrc_path = (char *)malloc(len + 5);
    if (!lrc_path) return false;

    strcpy(lrc_path, audio_path);

    char *dot = strrchr(lrc_path, '.');
    if (dot) {
        strcpy(dot, ".lrc");
    } else {
        strcat(lrc_path, ".lrc");
    }

    bool result = lrc_parse_file(lrc_path);
    free(lrc_path);
    return result;
}

void lrc_update_time(uint32_t current_ms)
{
    if (g_lrc_count == 0 || !ui_lrc_list) return;

    int active_idx = -1;
    for (int i = 0; i < g_lrc_count; i++) {
        if (current_ms >= g_lrc_lines[i].time_ms) {
            active_idx = i;
        } else {
            break;
        }
    }

    if (active_idx != g_current_index && active_idx >= 0) {
        if (g_current_index >= 0 && g_current_index < g_lrc_count && g_lrc_labels[g_current_index]) {
            lv_obj_set_style_text_color(g_lrc_labels[g_current_index], lv_color_hex(0x888888), LV_PART_MAIN);
            lv_obj_set_style_text_opa(g_lrc_labels[g_current_index], 160, LV_PART_MAIN);
        }

        if (g_lrc_labels[active_idx]) {
            // 高亮当前播放行
            lv_obj_set_style_text_color(g_lrc_labels[active_idx], lv_color_hex(0xFFFFFF), LV_PART_MAIN);
            lv_obj_set_style_text_opa(g_lrc_labels[active_idx], 255, LV_PART_MAIN);

            // 精准垂直居中滚动
            lv_obj_scroll_to_view(g_lrc_labels[active_idx], LV_ANIM_ON);
        }

        g_current_index = active_idx;
    }
}