// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#ifndef UI_MUSIC_H
#define UI_MUSIC_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_music
extern void ui_music_screen_init(void);
extern void ui_music_screen_destroy(void);
extern void ui_event_music(lv_event_t * e);
extern lv_obj_t * ui_music;
extern lv_obj_t * ui_Container74;
extern lv_obj_t * ui_Container73;

// 歌词页面 UI 句柄
extern lv_obj_t * ui_Container_lrc;
extern lv_obj_t * ui_lrc_list;

extern lv_obj_t * ui_Container42;
extern lv_obj_t * ui_musci_changpian;
extern lv_obj_t * ui_music_info_label;
extern lv_obj_t * ui_Container39;
extern lv_obj_t * ui_Container40;
extern lv_obj_t * ui_music_cur_time;
extern lv_obj_t * ui_Container41;
extern lv_obj_t * ui_music_duration;
extern void ui_event_music_seek(lv_event_t * e);
extern lv_obj_t * ui_music_seek;
extern lv_obj_t * ui_Container33;
extern lv_obj_t * ui_Container35;
extern void ui_event_skip_back(lv_event_t * e);
extern lv_obj_t * ui_skip_back;
extern lv_obj_t * ui_Container37;
extern void ui_event_play(lv_event_t * e);
extern lv_obj_t * ui_play;
extern void ui_event_pause(lv_event_t * e);
extern lv_obj_t * ui_pause;
extern lv_obj_t * ui_Container38;
extern void ui_event_skip_forward(lv_event_t * e);
extern lv_obj_t * ui_skip_forward;
extern lv_obj_t * ui_Container43;
extern lv_obj_t * ui_Container46;
extern lv_obj_t * ui_Label32;
extern void ui_event_music_refresh(lv_event_t * e);
extern lv_obj_t * ui_music_refresh;
extern lv_obj_t * ui_Container45;
extern lv_obj_t * ui_simpleitem2;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_simple_item_text1;

// CUSTOM VARIABLES

// 歌词结构体与 API 声明
typedef struct {
    uint32_t time_ms;
    char *text;
} lrc_line_t;

bool lrc_parse(const char *lrc_str);
bool lrc_parse_file(const char *file_path);
bool lrc_parse_by_audio_path(const char *audio_path); // 传入音频路径自动加载同名 .lrc 歌词
void lrc_update_time(uint32_t current_ms);
void lrc_clear(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif