// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#ifndef UI_NES_GAME_H
#define UI_NES_GAME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_nes_game
extern void ui_nes_game_screen_init(void);
extern void ui_nes_game_screen_destroy(void);
extern void ui_event_nes_game(lv_event_t * e);
extern lv_obj_t * ui_nes_game;
extern lv_obj_t * ui_Container51;
extern lv_obj_t * ui_Container48;
extern lv_obj_t * ui_Label37;
extern void ui_event_game_refresh(lv_event_t * e);
extern lv_obj_t * ui_game_refresh;
extern lv_obj_t * ui_Container49;
extern lv_obj_t * ui_simpleitem3;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_simple_item_text3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

