// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#include "../ui.h"

lv_obj_t * ui_notification_panel = NULL;
lv_obj_t * ui_Container62 = NULL;
lv_obj_t * ui_notification_date_label = NULL;
lv_obj_t * ui_notification_week_label = NULL;
// event funtions

// build funtions

void ui_notification_panel_screen_init(void)
{
    ui_notification_panel = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_notification_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_notification_panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_notification_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_notification_panel, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container62 = lv_obj_create(ui_notification_panel);
    lv_obj_remove_style_all(ui_Container62);
    lv_obj_set_width(ui_Container62, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Container62, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Container62, 0);
    lv_obj_set_y(ui_Container62, lv_pct(5));
    lv_obj_set_align(ui_Container62, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Container62, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container62, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container62, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_notification_date_label = lv_label_create(ui_Container62);
    lv_obj_set_width(ui_notification_date_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_notification_date_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_notification_date_label, -64);
    lv_obj_set_y(ui_notification_date_label, -137);
    lv_obj_set_align(ui_notification_date_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_notification_date_label, "2026-10-01");
    lv_obj_set_style_text_color(ui_notification_date_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_notification_date_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_notification_date_label, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_notification_week_label = lv_label_create(ui_Container62);
    lv_obj_set_width(ui_notification_week_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_notification_week_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_notification_week_label, -76);
    lv_obj_set_y(ui_notification_week_label, -107);
    lv_obj_set_align(ui_notification_week_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_notification_week_label, "星期四");
    lv_obj_set_style_text_color(ui_notification_week_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_notification_week_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_notification_week_label, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_notification_panel_screen_destroy(void)
{
    if(ui_notification_panel) lv_obj_del(ui_notification_panel);

    // NULL screen variables
    ui_notification_panel = NULL;
    ui_Container62 = NULL;
    ui_notification_date_label = NULL;
    ui_notification_week_label = NULL;

}
