// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#ifndef UI_NOTIFICATION_PANEL_H
#define UI_NOTIFICATION_PANEL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_notification_panel
extern void ui_notification_panel_screen_init(void);
extern void ui_notification_panel_screen_destroy(void);
extern lv_obj_t * ui_notification_panel;
extern lv_obj_t * ui_Container62;
extern lv_obj_t * ui_notification_date_label;
extern lv_obj_t * ui_notification_week_label;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

