// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#ifndef UI_SETTINGS_H
#define UI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Settings
extern void ui_Settings_screen_init(void);
extern void ui_Settings_screen_destroy(void);
extern void ui_event_Settings(lv_event_t * e);
extern lv_obj_t * ui_Settings;
extern void ui_event_Container53(lv_event_t * e);
extern lv_obj_t * ui_Container53;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Image19;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

