// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#include "../ui.h"

lv_obj_t * ui_Settings = NULL;
lv_obj_t * ui_Container80 = NULL;
lv_obj_t * ui_Container81 = NULL;
lv_obj_t * ui_Container53 = NULL;
lv_obj_t * ui_Image17 = NULL;
lv_obj_t * ui_Label41 = NULL;
lv_obj_t * ui_Image19 = NULL;
// event funtions
void ui_event_Container53(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_wifi, LV_SCR_LOAD_ANIM_OVER_LEFT, 300, 0, &ui_wifi_screen_init);
    }
}

// build funtions

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Settings, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Settings, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    ui_object_set_themeable_style_property(ui_Settings, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_Settings, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Container80 = lv_obj_create(ui_Settings);
    lv_obj_remove_style_all(ui_Container80);
    lv_obj_set_height(ui_Container80, 25);
    lv_obj_set_width(ui_Container80, lv_pct(100));
    lv_obj_set_align(ui_Container80, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container80, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container80, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container80, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container81 = lv_obj_create(ui_Settings);
    lv_obj_remove_style_all(ui_Container81);
    lv_obj_set_width(ui_Container81, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container81, 1);
    lv_obj_set_align(ui_Container81, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container81, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container81, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container81, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container81, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container81, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container81, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container81, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container81, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container81, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container53 = lv_obj_create(ui_Container81);
    lv_obj_remove_style_all(ui_Container53);
    lv_obj_set_height(ui_Container53, 50);
    lv_obj_set_width(ui_Container53, lv_pct(100));
    lv_obj_set_flex_flow(ui_Container53, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container53, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container53, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Container53, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container53, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container53, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image17 = lv_image_create(ui_Container53);
    lv_image_set_src(ui_Image17, &ui_img_icon_wifi_png);
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Image17, 1);
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label41 = lv_label_create(ui_Container53);
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Label41, 2);
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "WIFI");

    ui_Image19 = lv_image_create(ui_Container53);
    lv_image_set_src(ui_Image19, &ui_img_icon_chevron_right_png);
    lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Image19, 1);
    lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Container53, ui_event_Container53, LV_EVENT_ALL, NULL);

}

void ui_Settings_screen_destroy(void)
{
    if(ui_Settings) lv_obj_del(ui_Settings);

    // NULL screen variables
    ui_Settings = NULL;
    ui_Container80 = NULL;
    ui_Container81 = NULL;
    ui_Container53 = NULL;
    ui_Image17 = NULL;
    ui_Label41 = NULL;
    ui_Image19 = NULL;

}
