// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#include "../ui.h"

lv_obj_t * ui_temp_RH = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_Container27 = NULL;
lv_obj_t * ui_temp_Arc = NULL;
lv_obj_t * ui_temp_text = NULL;
lv_obj_t * ui_temp_tip = NULL;
lv_obj_t * ui_Container28 = NULL;
lv_obj_t * ui_RH_Arc = NULL;
lv_obj_t * ui_RH_text = NULL;
lv_obj_t * ui_RH_tip = NULL;
lv_obj_t * ui_Container44 = NULL;
lv_obj_t * ui_hPa_Arc1 = NULL;
lv_obj_t * ui_hPa_text = NULL;
lv_obj_t * ui_hPa = NULL;
// event funtions
void ui_event_temp_RH(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        temp_RH_load(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        temp_RH_unload(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_launcher, LV_SCR_LOAD_ANIM_OUT_TOP, 300, 0, &ui_launcher_screen_init);
    }
}

// build funtions

void ui_temp_RH_screen_init(void)
{
    ui_temp_RH = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_temp_RH, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image9 = lv_image_create(ui_temp_RH);
    lv_image_set_src(ui_Image9, &ui_img_temp_rh_bg_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container27 = lv_obj_create(ui_temp_RH);
    lv_obj_remove_style_all(ui_Container27);
    lv_obj_set_width(ui_Container27, lv_pct(75));
    lv_obj_set_height(ui_Container27, lv_pct(50));
    lv_obj_set_flex_flow(ui_Container27, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container27, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container27, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_temp_Arc = lv_arc_create(ui_Container27);
    lv_obj_set_width(ui_temp_Arc, 120);
    lv_obj_set_height(ui_temp_Arc, 120);
    lv_obj_set_align(ui_temp_Arc, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_temp_Arc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_arc_set_value(ui_temp_Arc, 50);
    lv_arc_set_bg_angles(ui_temp_Arc, 90, 30);
    lv_obj_set_style_arc_color(ui_temp_Arc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_temp_Arc, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_temp_Arc, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_temp_Arc, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_temp_Arc, 200, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_temp_Arc, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_temp_Arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_temp_Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_temp_text = lv_label_create(ui_temp_Arc);
    lv_obj_set_width(ui_temp_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_temp_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp_text, "温度 20℃");
    lv_obj_set_style_text_color(ui_temp_text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temp_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temp_text, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp_tip = lv_label_create(ui_Container27);
    lv_obj_set_width(ui_temp_tip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp_tip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_temp_tip, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp_tip, "不冷不热，神仙天气");
    lv_obj_set_style_text_color(ui_temp_tip, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temp_tip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temp_tip, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container28 = lv_obj_create(ui_temp_RH);
    lv_obj_remove_style_all(ui_Container28);
    lv_obj_set_width(ui_Container28, lv_pct(75));
    lv_obj_set_height(ui_Container28, lv_pct(50));
    lv_obj_set_align(ui_Container28, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_flex_flow(ui_Container28, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container28, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container28, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RH_Arc = lv_arc_create(ui_Container28);
    lv_obj_set_width(ui_RH_Arc, 120);
    lv_obj_set_height(ui_RH_Arc, 120);
    lv_obj_set_x(ui_RH_Arc, 0);
    lv_obj_set_y(ui_RH_Arc, 10);
    lv_obj_set_align(ui_RH_Arc, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_RH_Arc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_arc_set_value(ui_RH_Arc, 50);
    lv_obj_set_style_arc_color(ui_RH_Arc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_RH_Arc, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_RH_Arc, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_RH_Arc, lv_color_hex(0x0094FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_RH_Arc, 200, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_RH_Arc, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_RH_Arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RH_Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_RH_text = lv_label_create(ui_RH_Arc);
    lv_obj_set_width(ui_RH_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RH_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RH_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RH_text, "湿度 50%");
    lv_obj_set_style_text_color(ui_RH_text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RH_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RH_text, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RH_tip = lv_label_create(ui_Container28);
    lv_obj_set_width(ui_RH_tip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RH_tip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RH_tip, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RH_tip, "非常潮湿，注意除湿防霉");
    lv_obj_set_style_text_color(ui_RH_tip, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RH_tip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RH_tip, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container44 = lv_obj_create(ui_temp_RH);
    lv_obj_remove_style_all(ui_Container44);
    lv_obj_set_width(ui_Container44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Container44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Container44, -5);
    lv_obj_set_y(ui_Container44, lv_pct(0));
    lv_obj_set_align(ui_Container44, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_Container44, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container44, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container44, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hPa_Arc1 = lv_arc_create(ui_Container44);
    lv_obj_set_width(ui_hPa_Arc1, 70);
    lv_obj_set_height(ui_hPa_Arc1, 70);
    lv_obj_set_x(ui_hPa_Arc1, 0);
    lv_obj_set_y(ui_hPa_Arc1, 10);
    lv_obj_set_align(ui_hPa_Arc1, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_hPa_Arc1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_arc_set_value(ui_hPa_Arc1, 50);
    lv_obj_set_style_arc_color(ui_hPa_Arc1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_hPa_Arc1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_hPa_Arc1, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_hPa_Arc1, lv_color_hex(0x0094FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_hPa_Arc1, 200, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_hPa_Arc1, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_hPa_Arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hPa_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_hPa_text = lv_label_create(ui_hPa_Arc1);
    lv_obj_set_width(ui_hPa_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hPa_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_hPa_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hPa_text, "0 hPa");
    lv_obj_set_style_text_color(ui_hPa_text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_hPa_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hPa_text, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hPa = lv_label_create(ui_Container44);
    lv_obj_set_width(ui_hPa, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hPa, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_hPa, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hPa, "气压");
    lv_obj_set_style_text_color(ui_hPa, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_hPa, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hPa, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_temp_RH, ui_event_temp_RH, LV_EVENT_ALL, NULL);

}

void ui_temp_RH_screen_destroy(void)
{
    if(ui_temp_RH) lv_obj_del(ui_temp_RH);

    // NULL screen variables
    ui_temp_RH = NULL;
    ui_Image9 = NULL;
    ui_Container27 = NULL;
    ui_temp_Arc = NULL;
    ui_temp_text = NULL;
    ui_temp_tip = NULL;
    ui_Container28 = NULL;
    ui_RH_Arc = NULL;
    ui_RH_text = NULL;
    ui_RH_tip = NULL;
    ui_Container44 = NULL;
    ui_hPa_Arc1 = NULL;
    ui_hPa_text = NULL;
    ui_hPa = NULL;

}
