// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#ifndef UI_TEMP_RH_H
#define UI_TEMP_RH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_temp_RH
extern void ui_temp_RH_screen_init(void);
extern void ui_temp_RH_screen_destroy(void);
extern void ui_event_temp_RH(lv_event_t * e);
extern lv_obj_t * ui_temp_RH;
extern lv_obj_t * ui_Container76;
extern lv_obj_t * ui_Container77;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Container27;
extern lv_obj_t * ui_temp_Arc;
extern lv_obj_t * ui_temp_text;
extern lv_obj_t * ui_temp_tip;
extern lv_obj_t * ui_Container28;
extern lv_obj_t * ui_RH_Arc;
extern lv_obj_t * ui_RH_text;
extern lv_obj_t * ui_RH_tip;
extern lv_obj_t * ui_Container44;
extern lv_obj_t * ui_hPa_Arc1;
extern lv_obj_t * ui_hPa_text;
extern lv_obj_t * ui_hPa;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

