// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#ifndef UI_WIFI_H
#define UI_WIFI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_wifi
extern void ui_wifi_screen_init(void);
extern void ui_wifi_screen_destroy(void);
extern void ui_event_wifi(lv_event_t * e);
extern lv_obj_t * ui_wifi;
extern lv_obj_t * ui_Container55;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_wifi_scan_list;
extern lv_obj_t * ui_wifi_scan_item;
extern lv_obj_t * ui_Container56;
extern lv_obj_t * ui_wifi_rssi;
extern lv_obj_t * ui_wifi_ssid;
extern lv_obj_t * ui_Container57;
extern lv_obj_t * ui_wifi_auth_mode;
extern lv_obj_t * ui_wifi_scan_item1;
extern lv_obj_t * ui_Container59;
extern lv_obj_t * ui_wifi_rssi1;
extern lv_obj_t * ui_wifi_ssid1;
extern lv_obj_t * ui_Container60;
extern lv_obj_t * ui_wifi_auth_mode1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

