// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#include "../ui.h"

lv_obj_t * ui_wifi_input_pwd = NULL;
lv_obj_t * ui_Container58 = NULL;
lv_obj_t * ui_wifi_pwd_TextArea = NULL;
lv_obj_t * ui_Checkbox1 = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
// event funtions
void ui_event_wifi_input_pwd(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_wifi, LV_SCR_LOAD_ANIM_OUT_RIGHT, 300, 0, &ui_wifi_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        wifi_input_pwd_unloaded(e);
    }
}

void ui_event_Checkbox1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        on_show_password_changed(e);
    }
}

void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        wifi_pwd_done(e);
    }
}

// build funtions

void ui_wifi_input_pwd_screen_init(void)
{
    ui_wifi_input_pwd = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_wifi_input_pwd, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container58 = lv_obj_create(ui_wifi_input_pwd);
    lv_obj_remove_style_all(ui_Container58);
    lv_obj_set_width(ui_Container58, lv_pct(100));
    lv_obj_set_height(ui_Container58, lv_pct(100));
    lv_obj_set_align(ui_Container58, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container58, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container58, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container58, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container58, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container58, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container58, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container58, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container58, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container58, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi_pwd_TextArea = lv_textarea_create(ui_Container58);
    lv_obj_set_width(ui_wifi_pwd_TextArea, lv_pct(90));
    lv_obj_set_height(ui_wifi_pwd_TextArea, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifi_pwd_TextArea, 0);
    lv_obj_set_y(ui_wifi_pwd_TextArea, 10);
    lv_obj_set_align(ui_wifi_pwd_TextArea, LV_ALIGN_TOP_MID);
    lv_textarea_set_placeholder_text(ui_wifi_pwd_TextArea, "password");
    lv_textarea_set_one_line(ui_wifi_pwd_TextArea, true);
    lv_textarea_set_password_mode(ui_wifi_pwd_TextArea, true);
    lv_obj_set_style_radius(ui_wifi_pwd_TextArea, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_wifi_pwd_TextArea, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wifi_pwd_TextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_wifi_pwd_TextArea, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_wifi_pwd_TextArea, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_wifi_pwd_TextArea, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_wifi_pwd_TextArea, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_wifi_pwd_TextArea, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Checkbox1 = lv_checkbox_create(ui_Container58);
    lv_checkbox_set_text(ui_Checkbox1, "显示密码");
    lv_obj_set_width(ui_Checkbox1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_Checkbox1, 40);
    lv_obj_set_x(ui_Checkbox1, lv_pct(5));
    lv_obj_add_flag(ui_Checkbox1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Checkbox1, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_width(ui_Checkbox1, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Checkbox1, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Checkbox1, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Checkbox1, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_Keyboard1 = lv_keyboard_create(ui_wifi_input_pwd);
    lv_keyboard_set_mode(ui_Keyboard1, LV_KEYBOARD_MODE_SPECIAL);
    lv_obj_set_height(ui_Keyboard1, 140);
    lv_obj_set_width(ui_Keyboard1, lv_pct(100));
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_pad_left(ui_Keyboard1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Keyboard1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Keyboard1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Keyboard1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Keyboard1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Keyboard1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Keyboard1, 2, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard1, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Keyboard1, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Keyboard1, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Keyboard1, 2, LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0x6A6A6A), LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Keyboard1, 255, LV_PART_ITEMS | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_Checkbox1, ui_event_Checkbox1, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_wifi_pwd_TextArea);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifi_input_pwd, ui_event_wifi_input_pwd, LV_EVENT_ALL, NULL);

}

void ui_wifi_input_pwd_screen_destroy(void)
{
    if(ui_wifi_input_pwd) lv_obj_del(ui_wifi_input_pwd);

    // NULL screen variables
    ui_wifi_input_pwd = NULL;
    ui_Container58 = NULL;
    ui_wifi_pwd_TextArea = NULL;
    ui_Checkbox1 = NULL;
    ui_Keyboard1 = NULL;

}
