// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#include "../ui.h"

lv_obj_t * ui_wifi = NULL;
lv_obj_t * ui_Container82 = NULL;
lv_obj_t * ui_Container83 = NULL;
lv_obj_t * ui_Container55 = NULL;
lv_obj_t * ui_Label43 = NULL;
lv_obj_t * ui_wifi_scan_list = NULL;
lv_obj_t * ui_wifi_scan_item1 = NULL;
lv_obj_t * ui_Container59 = NULL;
lv_obj_t * ui_wifi_rssi1 = NULL;
lv_obj_t * ui_wifi_ssid1 = NULL;
lv_obj_t * ui_Container60 = NULL;
lv_obj_t * ui_wifi_auth_mode1 = NULL;
lv_obj_t * ui_wifi_scan_item2 = NULL;
lv_obj_t * ui_Container56 = NULL;
lv_obj_t * ui_wifi_rssi = NULL;
lv_obj_t * ui_wifi_ssid = NULL;
lv_obj_t * ui_Container57 = NULL;
lv_obj_t * ui_wifi_auth_mode = NULL;
// event funtions
void ui_event_wifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_OUT_RIGHT, 300, 0, &ui_Settings_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        wifi_loaded(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        wifi_unloaded(e);
    }
}

// build funtions

void ui_wifi_screen_init(void)
{
    ui_wifi = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_wifi, LV_OBJ_FLAG_PRESS_LOCK);      /// Flags
    lv_obj_set_flex_flow(ui_wifi, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_wifi, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    ui_object_set_themeable_style_property(ui_wifi, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_wifi, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Container82 = lv_obj_create(ui_wifi);
    lv_obj_remove_style_all(ui_Container82);
    lv_obj_set_height(ui_Container82, 25);
    lv_obj_set_width(ui_Container82, lv_pct(100));
    lv_obj_set_align(ui_Container82, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container82, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container82, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container82, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container83 = lv_obj_create(ui_wifi);
    lv_obj_remove_style_all(ui_Container83);
    lv_obj_set_width(ui_Container83, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container83, 1);
    lv_obj_set_align(ui_Container83, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container83, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container83, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container83, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container55 = lv_obj_create(ui_Container83);
    lv_obj_remove_style_all(ui_Container55);
    lv_obj_set_height(ui_Container55, 50);
    lv_obj_set_width(ui_Container55, lv_pct(100));
    lv_obj_remove_flag(ui_Container55, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Container55, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_azure);
    ui_object_set_themeable_style_property(ui_Container55, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_azure);

    ui_Label43 = lv_label_create(ui_Container55);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "WIFI");
    lv_obj_remove_flag(ui_Label43, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label43, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label43, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi_scan_list = lv_obj_create(ui_Container83);
    lv_obj_remove_style_all(ui_wifi_scan_list);
    lv_obj_set_width(ui_wifi_scan_list, lv_pct(100));
    lv_obj_set_flex_grow(ui_wifi_scan_list, 1);
    lv_obj_set_align(ui_wifi_scan_list, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_wifi_scan_list, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_wifi_scan_list, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_wifi_scan_list,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_wifi_scan_item1 = lv_obj_create(ui_wifi_scan_list);
    lv_obj_remove_style_all(ui_wifi_scan_item1);
    lv_obj_set_height(ui_wifi_scan_item1, 43);
    lv_obj_set_width(ui_wifi_scan_item1, lv_pct(100));
    lv_obj_add_flag(ui_wifi_scan_item1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_wifi_scan_item1, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_wifi_scan_item1, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container59 = lv_obj_create(ui_wifi_scan_item1);
    lv_obj_remove_style_all(ui_Container59);
    lv_obj_set_height(ui_Container59, 40);
    lv_obj_set_width(ui_Container59, lv_pct(90));
    lv_obj_set_align(ui_Container59, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Container59, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container59, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container59, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container59, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container59, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container59, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi_rssi1 = lv_image_create(ui_Container59);
    lv_image_set_src(ui_wifi_rssi1, &ui_img_icon_wifi_black_png);
    lv_obj_set_height(ui_wifi_rssi1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_wifi_rssi1, 1);
    lv_obj_set_align(ui_wifi_rssi1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_wifi_rssi1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_wifi_ssid1 = lv_label_create(ui_Container59);
    lv_obj_set_height(ui_wifi_ssid1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_wifi_ssid1, 3);
    lv_obj_set_align(ui_wifi_ssid1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifi_ssid1, "text");
    lv_obj_remove_flag(ui_wifi_ssid1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    ui_Container60 = lv_obj_create(ui_Container59);
    lv_obj_remove_style_all(ui_Container60);
    lv_obj_set_height(ui_Container60, 40);
    lv_obj_set_flex_grow(ui_Container60, 1);
    lv_obj_set_align(ui_Container60, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container60, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_wifi_auth_mode1 = lv_image_create(ui_Container60);
    lv_image_set_src(ui_wifi_auth_mode1, &ui_img_icon_circle_check_png);
    lv_obj_set_width(ui_wifi_auth_mode1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifi_auth_mode1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wifi_auth_mode1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_wifi_auth_mode1,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_wifi_scan_item2 = lv_obj_create(ui_wifi_scan_list);
    lv_obj_remove_style_all(ui_wifi_scan_item2);
    lv_obj_set_height(ui_wifi_scan_item2, 43);
    lv_obj_set_width(ui_wifi_scan_item2, lv_pct(100));
    lv_obj_add_flag(ui_wifi_scan_item2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_wifi_scan_item2, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_wifi_scan_item2, &ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container56 = lv_obj_create(ui_wifi_scan_item2);
    lv_obj_remove_style_all(ui_Container56);
    lv_obj_set_height(ui_Container56, 40);
    lv_obj_set_width(ui_Container56, lv_pct(90));
    lv_obj_set_align(ui_Container56, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Container56, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container56, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container56, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container56, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container56, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container56, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi_rssi = lv_image_create(ui_Container56);
    lv_image_set_src(ui_wifi_rssi, &ui_img_icon_wifi_black_png);
    lv_obj_set_height(ui_wifi_rssi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_wifi_rssi, 1);
    lv_obj_set_align(ui_wifi_rssi, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_wifi_rssi, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_wifi_ssid = lv_label_create(ui_Container56);
    lv_obj_set_height(ui_wifi_ssid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_wifi_ssid, 3);
    lv_obj_set_align(ui_wifi_ssid, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifi_ssid, "text");
    lv_obj_remove_flag(ui_wifi_ssid, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    ui_Container57 = lv_obj_create(ui_Container56);
    lv_obj_remove_style_all(ui_Container57);
    lv_obj_set_height(ui_Container57, 40);
    lv_obj_set_flex_grow(ui_Container57, 1);
    lv_obj_set_align(ui_Container57, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container57, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_wifi_auth_mode = lv_image_create(ui_Container57);
    lv_image_set_src(ui_wifi_auth_mode, &ui_img_icon_lock_png);
    lv_obj_set_width(ui_wifi_auth_mode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifi_auth_mode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wifi_auth_mode, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_wifi_auth_mode,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    lv_obj_add_event_cb(ui_wifi, ui_event_wifi, LV_EVENT_ALL, NULL);

}

void ui_wifi_screen_destroy(void)
{
    if(ui_wifi) lv_obj_del(ui_wifi);

    // NULL screen variables
    ui_wifi = NULL;
    ui_Container82 = NULL;
    ui_Container83 = NULL;
    ui_Container55 = NULL;
    ui_Label43 = NULL;
    ui_wifi_scan_list = NULL;
    ui_wifi_scan_item1 = NULL;
    ui_Container59 = NULL;
    ui_wifi_rssi1 = NULL;
    ui_wifi_ssid1 = NULL;
    ui_Container60 = NULL;
    ui_wifi_auth_mode1 = NULL;
    ui_wifi_scan_item2 = NULL;
    ui_Container56 = NULL;
    ui_wifi_rssi = NULL;
    ui_wifi_ssid = NULL;
    ui_Container57 = NULL;
    ui_wifi_auth_mode = NULL;

}
