// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#include "../../ui.h"

lv_obj_t * ui_Settings = NULL;

// event funtions
void ui_event_wifi_item(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_wifi, LV_SCR_LOAD_ANIM_OVER_LEFT, 300, 0, &ui_wifi_screen_init);
    }
}

void ui_device_info_item(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_device_info, LV_SCR_LOAD_ANIM_OVER_LEFT, 300, 0, &ui_device_info_init);
    }
}

static lv_obj_t * create_item(lv_obj_t * parent, const void *icon, const char *text)
{
    lv_obj_t *item = lv_obj_create(parent);
    lv_obj_remove_style_all(item);
    lv_obj_set_height(item, 50);
    lv_obj_set_width(item, lv_pct(100));
    lv_obj_set_flex_flow(item, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(item, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(item, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(item, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(item, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(item, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *icon_obj = lv_image_create(item);
    lv_image_set_src(icon_obj, icon);
    lv_obj_set_height(icon_obj, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(icon_obj, 1);
    lv_obj_set_align(icon_obj, LV_ALIGN_CENTER);
    lv_obj_remove_flag(icon_obj, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_t *item_label = lv_label_create(item);
    lv_obj_set_height(item_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(item_label, 2);
    lv_obj_set_align(item_label, LV_ALIGN_CENTER);
    lv_label_set_text(item_label, text);
    lv_obj_set_style_text_font(item_label, ui_font_simhei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *ui_Image19 = lv_image_create(item);
    lv_image_set_src(ui_Image19, &ui_img_icon_chevron_right_png);
    lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Image19, 1);
    lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_CLICKABLE);      /// Flags

    return item;
}

// build funtions

void ui_Settings_screen_init(void)
{
    ui_Settings =  ui_base_create(NULL);

    lv_obj_t * display = ui_comp_get_child(ui_Settings, UI_COMP_DISPLAY_CONTAINER);
    ui_object_set_themeable_style_property(display, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(display, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_pad_left(display, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(display, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(display, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(display, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(display, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(display, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * wifi_item = create_item(display, &ui_img_icon_wifi_png, "Wi-Fi");
    lv_obj_t * device_info_item = create_item(display, &ui_img_icon_device_info, "设备信息");

    lv_obj_add_event_cb(wifi_item, ui_event_wifi_item, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(device_info_item, ui_device_info_item, LV_EVENT_ALL, NULL);
}

void ui_Settings_screen_destroy(void)
{
    if(ui_Settings) lv_obj_del(ui_Settings);

    // NULL screen variables
    ui_Settings = NULL;


}
