// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#ifndef UI_WIFI_INPUT_PWD_H
#define UI_WIFI_INPUT_PWD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_wifi_input_pwd
extern void ui_wifi_input_pwd_screen_init(void);
extern void ui_wifi_input_pwd_screen_destroy(void);
extern void ui_event_wifi_input_pwd(lv_event_t * e);
extern lv_obj_t * ui_wifi_input_pwd;
extern lv_obj_t * ui_Container84;
extern lv_obj_t * ui_Container85;
extern lv_obj_t * ui_Container58;
extern lv_obj_t * ui_wifi_pwd_TextArea;
extern void ui_event_Checkbox1(lv_event_t * e);
extern lv_obj_t * ui_Checkbox1;
extern void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

