// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_simple_init(dispp);
    lv_disp_set_theme(dispp, theme);
    ui_boot_screen_init();
    ui_launcher_screen_init();
    ui_calculator_screen_init();
    ui_temp_RH_screen_init();
    ui_health_screen_init();
    ui_music_screen_init();
    ui_nes_game_screen_init();
    ui_gaming_screen_init();
    ui_file_manager_screen_init();
    ui_Settings_screen_init();
    ui_wifi_screen_init();
    ui_wifi_input_pwd_screen_init();
    ui_calendar_screen_init();
    ui_notification_panel_screen_init();
    ui_clock_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_boot);
}

void ui_destroy(void)
{
    ui_boot_screen_destroy();
    ui_launcher_screen_destroy();
    ui_calculator_screen_destroy();
    ui_temp_RH_screen_destroy();
    ui_health_screen_destroy();
    ui_music_screen_destroy();
    ui_nes_game_screen_destroy();
    ui_gaming_screen_destroy();
    ui_file_manager_screen_destroy();
    ui_Settings_screen_destroy();
    ui_wifi_screen_destroy();
    ui_wifi_input_pwd_screen_destroy();
    ui_calendar_screen_destroy();
    ui_notification_panel_screen_destroy();
    ui_clock_screen_destroy();
}
