// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#ifndef _XIAOCAIUI_UI_H
#define _XIAOCAIUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_boot.h"
#include "screens/ui_launcher.h"
#include "screens/ui_calculator.h"
#include "screens/ui_temp_RH.h"
#include "screens/ui_health.h"
#include "screens/ui_music.h"
#include "screens/ui_nes_game.h"
#include "screens/ui_gaming.h"
#include "screens/ui_file_manager.h"
#include "screens/ui_Settings.h"
#include "screens/ui_wifi.h"
#include "screens/ui_wifi_input_pwd.h"
#include "screens/ui_calendar.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_apple_logo_png);    // assets/apple_logo.png
LV_IMG_DECLARE(ui_img_launcher_background_png);    // assets/launcher_background.png
LV_IMG_DECLARE(ui_img_app_settings_png);    // assets/app_settings.png
LV_IMG_DECLARE(ui_img_app_clock_png);    // assets/app_clock.png
LV_IMG_DECLARE(ui_img_1205787433);    // assets/icon_temp&RH.png
LV_IMG_DECLARE(ui_img_app_health_png);    // assets/app_health.png
LV_IMG_DECLARE(ui_img_app_game_png);    // assets/app_game.png
LV_IMG_DECLARE(ui_img_app_file_manager_png);    // assets/app_file_manager.png
LV_IMG_DECLARE(ui_img_app_calc_png);    // assets/app_calc.png
LV_IMG_DECLARE(ui_img_app_calendar_png);    // assets/app_calendar.png
LV_IMG_DECLARE(ui_img_app_music_png);    // assets/app_music.png
LV_IMG_DECLARE(ui_img_icon_wifi_small_png);    // assets/icon_wifi_small.png
LV_IMG_DECLARE(ui_img_icon_volume_png);    // assets/icon_volume.png
LV_IMG_DECLARE(ui_img_temp_rh_bg_png);    // assets/temp_RH_bg.png
LV_IMG_DECLARE(ui_img_icon_heart_rate_png);    // assets/icon_heart_rate.png
LV_IMG_DECLARE(ui_img_icon_spo2_png);    // assets/icon_spo2.png
LV_IMG_DECLARE(ui_img_music_changpian_png);    // assets/music_changpian.png
LV_IMG_DECLARE(ui_img_1330499080);    // assets/skip-back.png
LV_IMG_DECLARE(ui_img_play_png);    // assets/play.png
LV_IMG_DECLARE(ui_img_pause_png);    // assets/pause.png
LV_IMG_DECLARE(ui_img_1259189730);    // assets/skip-forward.png
LV_IMG_DECLARE(ui_img_icon_refresh_png);    // assets/icon_refresh.png
LV_IMG_DECLARE(ui_img_item_music_png);    // assets/item_music.png
LV_IMG_DECLARE(ui_img_item_game_png);    // assets/item_game.png
LV_IMG_DECLARE(ui_img_icon_wifi_png);    // assets/icon_wifi.png
LV_IMG_DECLARE(ui_img_icon_chevron_right_png);    // assets/icon_chevron_right.png
LV_IMG_DECLARE(ui_img_icon_wifi_black_png);    // assets/icon_wifi_black.png
LV_IMG_DECLARE(ui_img_icon_lock_png);    // assets/icon_lock.png
LV_IMG_DECLARE(ui_img_icon_circle_check_png);    // assets/icon_circle_check.png

// FONTS
LV_FONT_DECLARE(ui_font_simhei14);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
