// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: xiaocaiUI

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void bootinit(lv_event_t * e);
void volume_change(lv_event_t * e);
void temp_RH_load(lv_event_t * e);
void temp_RH_unload(lv_event_t * e);
void music_loaded(lv_event_t * e);
void music_unloaded(lv_event_t * e);
void music_seek_released(lv_event_t * e);
void music_seek_pressed(lv_event_t * e);
void music_seek_value_changed(lv_event_t * e);
void music_action(lv_event_t * e);
void music_list_refresh(lv_event_t * e);
void game_loaded(lv_event_t * e);
void game_list_refresh(lv_event_t * e);
void gaming_paused(lv_event_t * e);
void gaming_loaded(lv_event_t * e);
void gaming_resume(lv_event_t * e);
void change_game_sound(lv_event_t * e);
void gaming_exit(lv_event_t * e);
void file_manager_loaded(lv_event_t * e);
void file_manager_unloaded(lv_event_t * e);
void file_del(lv_event_t * e);
void file_act_close(lv_event_t * e);
void wifi_loaded(lv_event_t * e);
void wifi_unloaded(lv_event_t * e);
void wifi_input_pwd_unloaded(lv_event_t * e);
void on_show_password_changed(lv_event_t * e);
void wifi_pwd_done(lv_event_t * e);
void calendar_loaded(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
